-- Lock Database
CREATE TABLE ca_account_t (FIN_COA_CD VARCHAR2(2) DEFAULT '' NOT NULL, ACCOUNT_NBR VARCHAR2(10) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, ACCOUNT_NM VARCHAR2(40), ORG_CD VARCHAR2(10), ACCT_CREATE_DT TIMESTAMP, ACCT_EFFECT_DT TIMESTAMP, ACCT_EXPIRATION_DT TIMESTAMP, ACCT_CLOSED_IND VARCHAR2(1));
CREATE TABLE ca_chart_t (FIN_COA_CD VARCHAR2(2) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, FIN_COA_DESC VARCHAR2(40), FIN_COA_ACTIVE_CD VARCHAR2(1), CONSTRAINT PK_CA_CHART_T PRIMARY KEY (FIN_COA_CD));
CREATE TABLE ca_object_code_t (UNIV_FISCAL_YR DECIMAL(4,0) DEFAULT 0 NOT NULL, FIN_COA_CD VARCHAR2(2) DEFAULT '' NOT NULL, FIN_OBJECT_CD VARCHAR2(5) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, FIN_OBJ_CD_NM VARCHAR2(40), FIN_OBJ_CD_SHRT_NM VARCHAR2(12), FIN_OBJ_ACTIVE_CD VARCHAR2(1));
CREATE TABLE ca_org_t (FIN_COA_CD VARCHAR2(2) DEFAULT '' NOT NULL, ORG_CD VARCHAR2(10) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, ORG_NM VARCHAR2(40), ORG_ACTIVE_CD VARCHAR2(1));
CREATE TABLE ca_project_t (PROJECT_CD VARCHAR2(10) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, PROJECT_NM VARCHAR2(40), FIN_COA_CD VARCHAR2(2), ORG_CD VARCHAR2(10), PROJ_ACTIVE_CD VARCHAR2(1), PROJECT_DESC VARCHAR2(400), CONSTRAINT PK_CA_PROJECT_T PRIMARY KEY (PROJECT_CD));
CREATE TABLE ca_sub_acct_t (FIN_COA_CD VARCHAR2(2) DEFAULT '' NOT NULL, ACCOUNT_NBR VARCHAR2(10) DEFAULT '' NOT NULL, SUB_ACCT_NBR VARCHAR2(5) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, SUB_ACCT_NM VARCHAR2(40), SUB_ACCT_ACTV_CD VARCHAR2(1));
CREATE TABLE ca_sub_object_cd_t (UNIV_FISCAL_YR DECIMAL(4,0) DEFAULT 0 NOT NULL, FIN_COA_CD VARCHAR2(2) DEFAULT '' NOT NULL, ACCOUNT_NBR VARCHAR2(10) DEFAULT '' NOT NULL, FIN_OBJECT_CD VARCHAR2(5) DEFAULT '' NOT NULL, FIN_SUB_OBJ_CD VARCHAR2(3) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, FIN_SUB_OBJ_CD_NM VARCHAR2(40), FIN_SUBOBJ_SHRT_NM VARCHAR2(12), FIN_SUBOBJ_ACTV_CD VARCHAR2(1));
CREATE SEQUENCE hr_dept_earn_code_s START WITH 1000;

CREATE TABLE hr_dept_earn_code_t (hr_dept_earn_code_id NUMBER(38,0) NOT NULL, dept VARCHAR2(21) NOT NULL, hr_sal_group VARCHAR2(10) NOT NULL, earn_code VARCHAR2(3) NOT NULL, employee VARCHAR2(1) DEFAULT 'N', approver VARCHAR2(1) DEFAULT 'N', org_admin VARCHAR2(1) DEFAULT 'N', OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1, location VARCHAR2(10), active VARCHAR2(1) DEFAULT 'N', effdt DATE, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_HR_DEPT_EARN_CODE_T PRIMARY KEY (hr_dept_earn_code_id));
CREATE SEQUENCE hr_dept_s START WITH 1000;

CREATE TABLE hr_dept_t (HR_DEPT_ID NUMBER(38,0) NOT NULL, dept VARCHAR2(21), DESCRIPTION VARCHAR2(75), ORG VARCHAR2(10), CHART VARCHAR2(10), effdt DATE, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, active VARCHAR2(1) DEFAULT 'N', location VARCHAR2(20) NOT NULL, CONSTRAINT PK_HR_DEPT_T PRIMARY KEY (HR_DEPT_ID));
CREATE SEQUENCE hr_earn_code_s START WITH 1000;

CREATE TABLE hr_earn_code_t (hr_earn_code_id INTEGER NOT NULL, earn_code VARCHAR2(3) NOT NULL, descr VARCHAR2(30), effdt DATE, ovt_earn_code CHAR(1) DEFAULT 'N' NOT NULL, record_time VARCHAR2(1) DEFAULT 'N', record_amount VARCHAR2(1) DEFAULT 'N', record_hours VARCHAR2(1) DEFAULT 'N', ACTIVE VARCHAR2(1), OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, ACCRUAL_CATEGORY VARCHAR2(3), inflate_min_hours DECIMAL(3,2) DEFAULT 0 NOT NULL, inflate_factor DECIMAL(3,2) DEFAULT 1 NOT NULL, CONSTRAINT PK_HR_EARN_CODE_T PRIMARY KEY (hr_earn_code_id));
CREATE SEQUENCE hr_earn_group_def_s START WITH 1000;

CREATE TABLE hr_earn_group_def_t (hr_earn_group_id NUMBER(38,0) NOT NULL, earn_code VARCHAR2(3), OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1, hr_earn_group_def_id NUMBER(38,0) NOT NULL, CONSTRAINT PK_HR_EARN_GROUP_DEF_T PRIMARY KEY (hr_earn_group_def_id));
CREATE SEQUENCE hr_earn_group_s START WITH 1000;

CREATE TABLE hr_earn_group_t (hr_earn_group_id NUMBER(38,0) NOT NULL, earn_group VARCHAR2(10), descr VARCHAR2(30), show_summary VARCHAR2(1) DEFAULT 'N', effdt DATE, active VARCHAR2(1), OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_HR_EARN_GROUP_T PRIMARY KEY (hr_earn_group_id));
CREATE SEQUENCE hr_holiday_calendar_dates_s START WITH 1000;

CREATE TABLE hr_holiday_calendar_dates_t (HR_HOLIDAY_CALENDAR_DATES_ID NUMBER(38,0) NOT NULL, HOLIDAY_DATE DATE NOT NULL, HOLIDAY_DESC VARCHAR2(30) NOT NULL, HR_HOLIDAY_CALENDAR_ID INTEGER NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, HOLIDAY_HRS DECIMAL(4,2) NOT NULL, CONSTRAINT PK_HR_HOLIDAY_CALENDAR_DATES_T PRIMARY KEY (HR_HOLIDAY_CALENDAR_DATES_ID));
CREATE SEQUENCE hr_holiday_calendar_s START WITH 1000;

CREATE TABLE hr_holiday_calendar_t (HR_HOLIDAY_CALENDAR_ID NUMBER(38,0) NOT NULL, HOLIDAY_CALENDAR_GROUP VARCHAR2(3) NOT NULL, DESCR VARCHAR2(30), location VARCHAR2(30), OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, active VARCHAR2(1) DEFAULT 'Y' NOT NULL, CONSTRAINT PK_HR_HOLIDAY_CALENDAR_T PRIMARY KEY (HR_HOLIDAY_CALENDAR_ID));
CREATE SEQUENCE hr_job_s START WITH 1000;

CREATE TABLE hr_job_t (HR_JOB_ID NUMBER(38,0) NOT NULL, PRINCIPAL_ID VARCHAR2(40), JOB_NUMBER NUMBER(38,0), EFFDT DATE DEFAULT to_date('0002-11-30', 'YYYY-MM-DD') NOT NULL, dept VARCHAR2(90) NOT NULL, HR_SAL_GROUP VARCHAR2(10), pay_grade VARCHAR2(20), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, comp_rate DECIMAL(18,6) DEFAULT 0, location VARCHAR2(20), std_hours DECIMAL(5,2), fte VARCHAR2(1), hr_paytype VARCHAR2(5), active VARCHAR2(1) DEFAULT 'N', primary_indicator VARCHAR2(1) DEFAULT 'N', position_nbr VARCHAR2(20), CONSTRAINT PK_HR_JOB_T PRIMARY KEY (HR_JOB_ID));
CREATE SEQUENCE hr_location_s START WITH 1000;

CREATE TABLE hr_location_t (hr_location_id NUMBER(38,0) NOT NULL, location VARCHAR2(20) NOT NULL, timezone VARCHAR2(30) DEFAULT 'America\Indianapolis' NOT NULL, description VARCHAR2(60) NOT NULL, effdt DATE NOT NULL, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, active CHAR(1) NOT NULL, user_principal_id VARCHAR2(40), CONSTRAINT PK_HR_LOCATION_T PRIMARY KEY (hr_location_id));
CREATE SEQUENCE hr_pay_grade_s START WITH 1000;

CREATE TABLE hr_pay_grade_t (hr_pay_grade_id NUMBER(38,0) NOT NULL, pay_grade VARCHAR2(20) NOT NULL, description VARCHAR2(40) NOT NULL, effdt DATE NOT NULL, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, active CHAR(1) NOT NULL, user_principal_id VARCHAR2(40), CONSTRAINT PK_HR_PAY_GRADE_T PRIMARY KEY (hr_pay_grade_id));
CREATE SEQUENCE hr_paytype_s START WITH 1000;

CREATE TABLE hr_paytype_t (HR_PAYTYPE_ID NUMBER(38,0) NOT NULL, PAYTYPE VARCHAR2(5) NOT NULL, DESCR VARCHAR2(90), REG_ERN_CODE VARCHAR2(3) NOT NULL, EFFDT DATE NOT NULL, TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, ACTIVE VARCHAR2(1) DEFAULT 'N', CONSTRAINT PK_HR_PAYTYPE_T PRIMARY KEY (HR_PAYTYPE_ID));
CREATE SEQUENCE hr_position_id_s START WITH 1000;

CREATE SEQUENCE hr_position_s START WITH 1000;

CREATE TABLE hr_position_t (HR_POSITION_ID NUMBER(38,0) NOT NULL, POSITION_NBR VARCHAR2(20) NOT NULL, DESCRIPTION VARCHAR2(40) NOT NULL, EFFDT DATE NOT NULL, TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, ACTIVE VARCHAR2(1) DEFAULT 'N', CONSTRAINT PK_HR_POSITION_T PRIMARY KEY (HR_POSITION_ID));
CREATE TABLE hr_principal_calendar_t (principal_id VARCHAR2(40) DEFAULT '' NOT NULL, py_calendar_group VARCHAR2(45) DEFAULT '' NOT NULL, holiday_calendar_group VARCHAR2(45), timezone VARCHAR2(30), EFFDT DATE DEFAULT to_date('0002-11-30', 'YYYY-MM-DD') NOT NULL, TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, active VARCHAR2(1) DEFAULT 'Y', CONSTRAINT PK_HR_PRINCIPAL_CALENDAR_T PRIMARY KEY (principal_id));
CREATE SEQUENCE hr_py_calendar_entries_s START WITH 1000;

CREATE TABLE hr_py_calendar_entries_t (hr_py_calendar_entry_id NUMBER(38,0) NOT NULL, hr_py_calendar_id NUMBER(38,0), py_calendar_group VARCHAR2(45) NOT NULL, begin_period_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, end_period_date TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL, initiate_date DATE, initiate_time DATE, end_pay_period_date DATE, end_pay_period_time DATE, employee_approval_date DATE, employee_approval_time DATE, supervisor_approval_date DATE, supervisor_approval_time DATE, CONSTRAINT PK_HR_PY_CALENDAR_ENTRIES_T PRIMARY KEY (hr_py_calendar_entry_id));
CREATE SEQUENCE hr_py_calendar_s START WITH 1000;

CREATE TABLE hr_py_calendar_t (hr_py_calendar_id NUMBER(38,0) NOT NULL, py_calendar_group VARCHAR2(45) NOT NULL, flsa_begin_day VARCHAR2(9) NOT NULL, flsa_begin_time DATE NOT NULL, active VARCHAR2(1) DEFAULT 'Y' NOT NULL, CONSTRAINT PK_HR_PY_CALENDAR_T PRIMARY KEY (hr_py_calendar_id));
CREATE TABLE hr_roles_group_t (principal_id VARCHAR2(20) NOT NULL, CONSTRAINT PK_HR_ROLES_GROUP_T PRIMARY KEY (principal_id));
CREATE SEQUENCE hr_roles_s START WITH 1000;

CREATE TABLE hr_roles_t (hr_roles_id NUMBER(38,0) NOT NULL, principal_id VARCHAR2(40), role_name VARCHAR2(20) NOT NULL, user_principal_id VARCHAR2(40), work_area NUMBER(38,0), dept VARCHAR2(21), chart VARCHAR2(10), effdt DATE NOT NULL, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, active VARCHAR2(1) DEFAULT 'Y' NOT NULL, position_nbr VARCHAR2(20), CONSTRAINT PK_HR_ROLES_T PRIMARY KEY (hr_roles_id));
CREATE SEQUENCE hr_sal_group_s START WITH 1000;

CREATE TABLE hr_sal_group_t (HR_SAL_GROUP_ID NUMBER(38,0) NOT NULL, HR_SAL_GROUP VARCHAR2(10) NOT NULL, EFFDT DATE NOT NULL, TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, ACTIVE VARCHAR2(1) NOT NULL, OBJ_ID VARCHAR2(38) DEFAULT '1' NOT NULL, VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, descr VARCHAR2(30), CONSTRAINT PK_HR_SAL_GROUP_T PRIMARY KEY (HR_SAL_GROUP_ID));
CREATE SEQUENCE hr_work_schedule_assign_s START WITH 1000;

CREATE TABLE hr_work_schedule_assign_t (HR_WORK_SCHEDULE_ASSIGNMENT_ID NUMBER(38,0) NOT NULL, HR_WORK_SCHEDULE NUMBER(38,0) NOT NULL, DEPT VARCHAR2(21) NOT NULL, WORK_AREA NUMBER(38,0), PRINCIPAL_ID VARCHAR2(40), USER_PRINCIPAL_ID VARCHAR2(40), ACTIVE VARCHAR2(1) DEFAULT 'Y' NOT NULL, EFFDT DATE DEFAULT to_date('0002-11-30', 'YYYY-MM-DD') NOT NULL, TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, CONSTRAINT PK_HR_WORK_SCHEDULE_ASSIGN_T PRIMARY KEY (HR_WORK_SCHEDULE_ASSIGNMENT_ID));
CREATE SEQUENCE hr_work_schedule_entry_s START WITH 1000;

CREATE TABLE hr_work_schedule_entry_t (HR_WORK_SCHEDULE_ENTRY_ID NUMBER(38,0) NOT NULL, HR_WORK_SCHEDULE NUMBER(38,0) NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, index_of_day DECIMAL(8,0) DEFAULT 0 NOT NULL, begin_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, end_time TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL, CONSTRAINT PK_HR_WORK_SCHEDULE_ENTRY_T PRIMARY KEY (HR_WORK_SCHEDULE_ENTRY_ID));
CREATE SEQUENCE hr_work_schedule_s START WITH 1000;

CREATE TABLE hr_work_schedule_t (HR_WORK_SCHEDULE_ID NUMBER(38,0) NOT NULL, HR_WORK_SCHEDULE NUMBER(38,0) NOT NULL, WORK_SCHEDULE_DESC VARCHAR2(30) NOT NULL, EFFDT DATE DEFAULT to_date('0002-11-30', 'YYYY-MM-DD') NOT NULL, ACTIVE VARCHAR2(1) DEFAULT 'N', OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_HR_WORK_SCHEDULE_T PRIMARY KEY (HR_WORK_SCHEDULE_ID));
CREATE TABLE kr_unittest_t (foo VARCHAR2(1));
CREATE TABLE krns_adhoc_rte_actn_recip_t (RECIP_TYP_CD DECIMAL(1,0) DEFAULT 0 NOT NULL, ACTN_RQST_CD VARCHAR2(30) DEFAULT '' NOT NULL, ACTN_RQST_RECIP_ID VARCHAR2(70) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, DOC_HDR_ID VARCHAR2(14) DEFAULT '' NOT NULL);
CREATE TABLE krns_att_t (NTE_ID DECIMAL(14,0) DEFAULT 0 NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, MIME_TYP VARCHAR2(255), FILE_NM VARCHAR2(250), ATT_ID VARCHAR2(36), FILE_SZ DECIMAL(14,0), ATT_TYP_CD VARCHAR2(40), CONSTRAINT PK_KRNS_ATT_T PRIMARY KEY (NTE_ID));
CREATE TABLE krns_doc_hdr_t (DOC_HDR_ID VARCHAR2(14) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, FDOC_DESC VARCHAR2(40), ORG_DOC_HDR_ID VARCHAR2(10), TMPL_DOC_HDR_ID VARCHAR2(14), EXPLANATION VARCHAR2(400), CONSTRAINT PK_KRNS_DOC_HDR_T PRIMARY KEY (DOC_HDR_ID));
CREATE SEQUENCE krns_lock_s START WITH 1000;

CREATE SEQUENCE krns_lookup_rslt_s START WITH 1000;

CREATE TABLE krns_lookup_rslt_t (LOOKUP_RSLT_ID VARCHAR2(14) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, PRNCPL_ID VARCHAR2(40) NOT NULL, LOOKUP_DT TIMESTAMP NOT NULL, SERIALZD_RSLTS CLOB, CONSTRAINT PK_KRNS_LOOKUP_RSLT_T PRIMARY KEY (LOOKUP_RSLT_ID));
CREATE TABLE krns_lookup_sel_t (LOOKUP_RSLT_ID VARCHAR2(14) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, PRNCPL_ID VARCHAR2(40) NOT NULL, LOOKUP_DT TIMESTAMP NOT NULL, SEL_OBJ_IDS CLOB, CONSTRAINT PK_KRNS_LOOKUP_SEL_T PRIMARY KEY (LOOKUP_RSLT_ID));
CREATE TABLE krns_maint_doc_att_t (DOC_HDR_ID VARCHAR2(14) DEFAULT '' NOT NULL, ATT_CNTNT BLOB NOT NULL, FILE_NM VARCHAR2(150), CNTNT_TYP VARCHAR2(255), OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, CONSTRAINT PK_KRNS_MAINT_DOC_ATT_T PRIMARY KEY (DOC_HDR_ID));
CREATE TABLE krns_maint_doc_t (DOC_HDR_ID VARCHAR2(14) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, DOC_CNTNT CLOB, CONSTRAINT PK_KRNS_MAINT_DOC_T PRIMARY KEY (DOC_HDR_ID));
CREATE SEQUENCE krns_maint_lock_s START WITH 1000;

CREATE TABLE krns_maint_lock_t (MAINT_LOCK_REP_TXT VARCHAR2(500), OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, DOC_HDR_ID VARCHAR2(14) NOT NULL, MAINT_LOCK_ID VARCHAR2(14) DEFAULT '' NOT NULL, CONSTRAINT PK_KRNS_MAINT_LOCK_T PRIMARY KEY (MAINT_LOCK_ID));
CREATE SEQUENCE krns_nte_s START WITH 1000;

CREATE TABLE krns_nte_t (NTE_ID DECIMAL(14,0) DEFAULT 0 NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, RMT_OBJ_ID VARCHAR2(36) NOT NULL, AUTH_PRNCPL_ID VARCHAR2(40) NOT NULL, POST_TS TIMESTAMP NOT NULL, NTE_TYP_CD VARCHAR2(4) NOT NULL, TXT VARCHAR2(800), PRG_CD VARCHAR2(1), TPC_TXT VARCHAR2(40), CONSTRAINT PK_KRNS_NTE_T PRIMARY KEY (NTE_ID));
CREATE TABLE krns_nte_typ_t (NTE_TYP_CD VARCHAR2(4) DEFAULT '' NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, TYP_DESC_TXT VARCHAR2(100), ACTV_IND VARCHAR2(1), CONSTRAINT PK_KRNS_NTE_TYP_T PRIMARY KEY (NTE_TYP_CD));
CREATE TABLE krns_pessimistic_lock_t (PESSIMISTIC_LOCK_ID DECIMAL(14,0) DEFAULT 0 NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, LOCK_DESC_TXT VARCHAR2(4000), DOC_HDR_ID VARCHAR2(14) NOT NULL, GNRT_DT TIMESTAMP NOT NULL, PRNCPL_ID VARCHAR2(40) NOT NULL, CONSTRAINT PK_KRNS_PESSIMISTIC_LOCK_T PRIMARY KEY (PESSIMISTIC_LOCK_ID));
CREATE TABLE krns_sesn_doc_t (SESN_DOC_ID VARCHAR2(40) DEFAULT '' NOT NULL, DOC_HDR_ID VARCHAR2(14) DEFAULT '' NOT NULL, PRNCPL_ID VARCHAR2(40) DEFAULT '' NOT NULL, IP_ADDR VARCHAR2(60) DEFAULT '' NOT NULL, SERIALZD_DOC_FRM BLOB, LAST_UPDT_DT TIMESTAMP, CONTENT_ENCRYPTED_IND CHAR(1) DEFAULT 'N');
CREATE SEQUENCE krsb_bam_parm_s START WITH 1000;

CREATE TABLE krsb_bam_parm_t (BAM_PARM_ID DECIMAL(14,0) DEFAULT 0 NOT NULL, BAM_ID DECIMAL(14,0) NOT NULL, PARM CLOB NOT NULL, CONSTRAINT PK_KRSB_BAM_PARM_T PRIMARY KEY (BAM_PARM_ID));
CREATE SEQUENCE krsb_bam_s START WITH 1000;

CREATE TABLE krsb_bam_t (BAM_ID DECIMAL(14,0) DEFAULT 0 NOT NULL, SVC_NM VARCHAR2(255) NOT NULL, SVC_URL VARCHAR2(500) NOT NULL, MTHD_NM VARCHAR2(2000) NOT NULL, THRD_NM VARCHAR2(500) NOT NULL, CALL_DT TIMESTAMP NOT NULL, TGT_TO_STR VARCHAR2(2000) NOT NULL, SRVR_IND DECIMAL(1,0) NOT NULL, EXCPN_TO_STR VARCHAR2(2000), EXCPN_MSG CLOB, CONSTRAINT PK_KRSB_BAM_T PRIMARY KEY (BAM_ID));
CREATE TABLE krsb_msg_pyld_t (MSG_QUE_ID DECIMAL(14,0) DEFAULT 0 NOT NULL, MSG_PYLD CLOB NOT NULL, CONSTRAINT PK_KRSB_MSG_PYLD_T PRIMARY KEY (MSG_QUE_ID));
CREATE SEQUENCE krsb_msg_que_s START WITH 1000;

CREATE TABLE krsb_msg_que_t (MSG_QUE_ID DECIMAL(14,0) DEFAULT 0 NOT NULL, DT TIMESTAMP NOT NULL, EXP_DT TIMESTAMP, PRIO DECIMAL(8,0) NOT NULL, STAT_CD CHAR(1) NOT NULL, RTRY_CNT DECIMAL(8,0) NOT NULL, IP_NBR VARCHAR2(2000) NOT NULL, SVC_NM VARCHAR2(255), SVC_NMSPC VARCHAR2(255) NOT NULL, SVC_MTHD_NM VARCHAR2(2000), APP_VAL_ONE VARCHAR2(2000), APP_VAL_TWO VARCHAR2(2000), VER_NBR DECIMAL(8,0) DEFAULT 0, CONSTRAINT PK_KRSB_MSG_QUE_T PRIMARY KEY (MSG_QUE_ID));
CREATE SEQUENCE krsb_svc_def_s START WITH 1000;

CREATE TABLE krsb_svc_def_t (SVC_DEF_ID DECIMAL(14,0) DEFAULT 0 NOT NULL, SVC_NM VARCHAR2(255) NOT NULL, SVC_URL VARCHAR2(500) NOT NULL, SRVR_IP VARCHAR2(40) NOT NULL, SVC_NMSPC VARCHAR2(255) NOT NULL, SVC_ALIVE DECIMAL(1,0) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 0, FLT_SVC_DEF_ID DECIMAL(14,0) NOT NULL, SVC_DEF_CHKSM VARCHAR2(30) NOT NULL, CONSTRAINT PK_KRSB_SVC_DEF_T PRIMARY KEY (SVC_DEF_ID));
CREATE SEQUENCE lm_accrual_categories_s START WITH 1000;

CREATE TABLE lm_accrual_categories_t (LM_ACCRUAL_CATEGORY_ID NUMBER(38,0) NOT NULL, ACCRUAL_CATEGORY VARCHAR2(3) NOT NULL, DESCR VARCHAR2(30) NOT NULL, EFFDT DATE NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, ACTIVE VARCHAR2(1) DEFAULT 'N', TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_LM_ACCRUAL_CATEGORIES_T PRIMARY KEY (LM_ACCRUAL_CATEGORY_ID));
CREATE SEQUENCE lm_accruals_s START WITH 1000;

CREATE TABLE lm_accruals_t (LM_ACCRUALS_ID NUMBER(38,0) NOT NULL, PRINCIPAL_ID VARCHAR2(21) NOT NULL, ACCRUAL_CATEGORY VARCHAR2(3) NOT NULL, EFFDT TIMESTAMP NOT NULL, HOURS_ACCRUED DECIMAL(6,2) NOT NULL, HOURS_TAKEN DECIMAL(6,2) NOT NULL, HOURS_ADJUST DECIMAL(6,2) NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, CONSTRAINT PK_LM_ACCRUALS_T PRIMARY KEY (LM_ACCRUALS_ID));
CREATE TABLE qrtz_blob_triggers (TRIGGER_NAME VARCHAR2(80) DEFAULT '' NOT NULL, TRIGGER_GROUP VARCHAR2(80) DEFAULT '' NOT NULL, BLOB_DATA BLOB);
CREATE TABLE qrtz_calendars (CALENDAR_NAME VARCHAR2(80) DEFAULT '' NOT NULL, CALENDAR BLOB NOT NULL, CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY (CALENDAR_NAME));
CREATE TABLE qrtz_cron_triggers (TRIGGER_NAME VARCHAR2(80) DEFAULT '' NOT NULL, TRIGGER_GROUP VARCHAR2(80) DEFAULT '' NOT NULL, CRON_EXPRESSION VARCHAR2(80) NOT NULL, TIME_ZONE_ID VARCHAR2(80));
CREATE TABLE qrtz_fired_triggers (ENTRY_ID VARCHAR2(95) DEFAULT '' NOT NULL, TRIGGER_NAME VARCHAR2(80) NOT NULL, TRIGGER_GROUP VARCHAR2(80) NOT NULL, IS_VOLATILE VARCHAR2(1) NOT NULL, INSTANCE_NAME VARCHAR2(80) NOT NULL, FIRED_TIME DECIMAL(13,0) NOT NULL, PRIORITY DECIMAL(13,0) NOT NULL, STATE VARCHAR2(16) NOT NULL, JOB_NAME VARCHAR2(80), JOB_GROUP VARCHAR2(80), IS_STATEFUL VARCHAR2(1), REQUESTS_RECOVERY VARCHAR2(1), CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY (ENTRY_ID));
CREATE TABLE qrtz_job_details (JOB_NAME VARCHAR2(80) DEFAULT '' NOT NULL, JOB_GROUP VARCHAR2(80) DEFAULT '' NOT NULL, DESCRIPTION VARCHAR2(120), JOB_CLASS_NAME VARCHAR2(128) NOT NULL, IS_DURABLE VARCHAR2(1) NOT NULL, IS_VOLATILE VARCHAR2(1) NOT NULL, IS_STATEFUL VARCHAR2(1) NOT NULL, REQUESTS_RECOVERY VARCHAR2(1) NOT NULL, JOB_DATA BLOB);
CREATE TABLE qrtz_job_listeners (JOB_NAME VARCHAR2(80) DEFAULT '' NOT NULL, JOB_GROUP VARCHAR2(80) DEFAULT '' NOT NULL, JOB_LISTENER VARCHAR2(80) DEFAULT '' NOT NULL);
CREATE TABLE qrtz_locks (LOCK_NAME VARCHAR2(40) DEFAULT '' NOT NULL, CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY (LOCK_NAME));
CREATE TABLE qrtz_paused_trigger_grps (TRIGGER_GROUP VARCHAR2(80) DEFAULT '' NOT NULL, CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY (TRIGGER_GROUP));
CREATE TABLE qrtz_scheduler_state (INSTANCE_NAME VARCHAR2(80) DEFAULT '' NOT NULL, LAST_CHECKIN_TIME DECIMAL(13,0) NOT NULL, CHECKIN_INTERVAL DECIMAL(13,0) NOT NULL, CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY (INSTANCE_NAME));
CREATE TABLE qrtz_simple_triggers (TRIGGER_NAME VARCHAR2(80) DEFAULT '' NOT NULL, TRIGGER_GROUP VARCHAR2(80) DEFAULT '' NOT NULL, REPEAT_COUNT DECIMAL(7,0) NOT NULL, REPEAT_INTERVAL DECIMAL(12,0) NOT NULL, TIMES_TRIGGERED DECIMAL(7,0) NOT NULL);
CREATE TABLE qrtz_trigger_listeners (TRIGGER_NAME VARCHAR2(80) DEFAULT '' NOT NULL, TRIGGER_GROUP VARCHAR2(80) DEFAULT '' NOT NULL, TRIGGER_LISTENER VARCHAR2(80) DEFAULT '' NOT NULL);
CREATE TABLE qrtz_triggers (TRIGGER_NAME VARCHAR2(80) DEFAULT '' NOT NULL, TRIGGER_GROUP VARCHAR2(80) DEFAULT '' NOT NULL, JOB_NAME VARCHAR2(80) NOT NULL, JOB_GROUP VARCHAR2(80) NOT NULL, IS_VOLATILE VARCHAR2(1) NOT NULL, DESCRIPTION VARCHAR2(120), NEXT_FIRE_TIME DECIMAL(13,0), PREV_FIRE_TIME DECIMAL(13,0), PRIORITY DECIMAL(13,0), TRIGGER_STATE VARCHAR2(16) NOT NULL, TRIGGER_TYPE VARCHAR2(8) NOT NULL, START_TIME DECIMAL(13,0) NOT NULL, END_TIME DECIMAL(13,0), CALENDAR_NAME VARCHAR2(80), MISFIRE_INSTR DECIMAL(2,0), JOB_DATA BLOB);
CREATE SEQUENCE tk_assign_acct_s START WITH 1000;

CREATE TABLE tk_assign_acct_t (TK_ASSIGN_ACCT_ID NUMBER(38,0) NOT NULL, FIN_COA_CD VARCHAR2(2), ACCOUNT_NBR VARCHAR2(7), SUB_ACCT_NBR VARCHAR2(5), FIN_OBJECT_CD VARCHAR2(4), FIN_SUB_OBJ_CD VARCHAR2(3), PROJECT_CD VARCHAR2(10), ORG_REF_ID VARCHAR2(8), PERCENT DECIMAL(5,2), TK_ASSIGNMENT_ID NUMBER(38,0) NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, EARN_CODE VARCHAR2(3), CONSTRAINT PK_TK_ASSIGN_ACCT_T PRIMARY KEY (TK_ASSIGN_ACCT_ID));
CREATE SEQUENCE tk_assignment_s START WITH 1000;

CREATE TABLE tk_assignment_t (TK_ASSIGNMENT_ID NUMBER(38,0) NOT NULL, PRINCIPAL_ID VARCHAR2(40), JOB_NUMBER NUMBER(38,0), EFFDT DATE DEFAULT to_date('0002-11-30', 'YYYY-MM-DD') NOT NULL, WORK_AREA NUMBER(38,0), TASK NUMBER(38,0), OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, active VARCHAR2(1) DEFAULT 'N', timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_TK_ASSIGNMENT_T PRIMARY KEY (TK_ASSIGNMENT_ID));
CREATE SEQUENCE tk_batch_job_entry_s START WITH 1000;

CREATE TABLE tk_batch_job_entry_t (TK_BATCH_JOB_ENTRY_ID NUMBER(38,0) NOT NULL, TK_BATCH_JOB_ID NUMBER(38,0) NOT NULL, document_id VARCHAR2(40), principal_id VARCHAR2(40), BATCH_JOB_ENTRY_STATUS VARCHAR2(1) NOT NULL, HR_PY_CALENDAR_ENTRY_ID NUMBER(38,0) NOT NULL, batch_job_exception VARCHAR2(100), IP_ADDRESS VARCHAR2(20) NOT NULL, BATCH_JOB_NAME VARCHAR2(40) NOT NULL, clock_log_id NUMBER(38,0), CONSTRAINT PK_TK_BATCH_JOB_ENTRY_T PRIMARY KEY (TK_BATCH_JOB_ENTRY_ID));
CREATE SEQUENCE tk_batch_job_s START WITH 1000;

CREATE TABLE tk_batch_job_t (TK_BATCH_JOB_ID NUMBER(38,0) NOT NULL, BATCH_JOB_NAME VARCHAR2(40) NOT NULL, BATCH_JOB_STATUS VARCHAR2(1) NOT NULL, HR_PY_CALENDAR_ENTRY_ID NUMBER(38,0) NOT NULL, TIME_ELAPSED NUMBER(38,0) NOT NULL, timestamp TIMESTAMP, CONSTRAINT PK_TK_BATCH_JOB_T PRIMARY KEY (TK_BATCH_JOB_ID));
CREATE SEQUENCE tk_clock_location_rl_s START WITH 1000;

CREATE TABLE tk_clock_location_rl_t (TK_CLOCK_LOC_RULE_ID NUMBER(38,0) NOT NULL, WORK_AREA NUMBER(38,0), PRINCIPAL_ID VARCHAR2(10), job_number NUMBER(38,0), EFFDT DATE, active VARCHAR2(1), IP_ADDRESS VARCHAR2(15), USER_PRINCIPAL_ID VARCHAR2(10), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, dept VARCHAR2(21));
CREATE SEQUENCE tk_clock_log_s START WITH 1000;

CREATE TABLE tk_clock_log_t (TK_CLOCK_LOG_ID NUMBER(38,0) NOT NULL, PRINCIPAL_ID VARCHAR2(40), JOB_NUMBER NUMBER(38,0), WORK_AREA NUMBER(38,0), TASK NUMBER(38,0), TK_WORK_AREA_ID NUMBER(38,0), TK_TASK_ID NUMBER(38,0), CLOCK_TS TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL, CLOCK_TS_TZ VARCHAR2(50), CLOCK_ACTION VARCHAR2(2), IP_ADDRESS VARCHAR2(15), HR_JOB_ID NUMBER(38,0), USER_PRINCIPAL_ID VARCHAR2(40), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, CONSTRAINT PK_TK_CLOCK_LOG_T PRIMARY KEY (TK_CLOCK_LOG_ID));
CREATE SEQUENCE tk_daily_overtime_rl_s START WITH 1000;

CREATE TABLE tk_daily_overtime_rl_t (tk_daily_overtime_rl_id NUMBER(38,0) NOT NULL, LOCATION VARCHAR2(40), PAYTYPE VARCHAR2(5), EFFDT DATE, USER_PRINCIPAL_ID VARCHAR2(10), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, DEPT VARCHAR2(21), WORK_AREA NUMBER(38,0), MAX_GAP DECIMAL(8,2), MIN_HOURS DECIMAL(2,0), ACTIVE VARCHAR2(1), FROM_EARN_GROUP VARCHAR2(10), EARN_CODE VARCHAR2(10), CONSTRAINT PK_TK_DAILY_OVERTIME_RL_T PRIMARY KEY (tk_daily_overtime_rl_id));
CREATE SEQUENCE tk_dept_lunch_rl_s START WITH 1000;

CREATE TABLE tk_dept_lunch_rl_t (TK_DEPT_LUNCH_RL_ID NUMBER(38,0) NOT NULL, DEPT VARCHAR2(21), WORK_AREA NUMBER(38,0), principal_id VARCHAR2(10) DEFAULT '' NOT NULL, job_number NUMBER(38,0), EFFDT DATE NOT NULL, REQUIRED_CLOCK_FL VARCHAR2(3), MAX_MINS DECIMAL(2,0), user_principal_id VARCHAR2(10), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, active VARCHAR2(1), SHIFT_HOURS DECIMAL(2,1), DEDUCTION_MINS DECIMAL(3,0), CONSTRAINT PK_TK_DEPT_LUNCH_RL_T PRIMARY KEY (TK_DEPT_LUNCH_RL_ID));
CREATE TABLE tk_document_header_t (DOCUMENT_ID VARCHAR2(14) NOT NULL, PRINCIPAL_ID VARCHAR2(40), PAY_END_DT TIMESTAMP, DOCUMENT_STATUS VARCHAR2(1), PAY_BEGIN_DT TIMESTAMP, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1, CONSTRAINT PK_TK_DOCUMENT_HEADER_T PRIMARY KEY (DOCUMENT_ID));
CREATE SEQUENCE tk_grace_period_rl_s START WITH 1000;

CREATE TABLE tk_grace_period_rl_t (TK_GRACE_PERIOD_RULE_ID NUMBER(38,0), EFFDT DATE, GRACE_MINS DECIMAL(2,0), HOUR_FACTOR DECIMAL(6,0), user_principal_id VARCHAR2(10), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, ACTIVE VARCHAR2(1));
CREATE SEQUENCE tk_holiday_calendar_dates_s START WITH 1000;

CREATE SEQUENCE tk_hour_detail_hist_s START WITH 1000;


CREATE TABLE tk_hour_detail_hist_t (TK_HOUR_DETAIL_HIST_ID NUMBER(38,0) NOT NULL, TK_HOUR_DETAIL_ID NUMBER(38,0) NOT NULL, EARN_CODE VARCHAR2(3), HOURS DECIMAL(5,2), amount DECIMAL(6,2) DEFAULT 0, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, ACTION_HISTORY VARCHAR2(15), MODIFIED_BY_PRINCIPAL_ID VARCHAR2(40), TIMESTAMP_MODIFIED TIMESTAMP DEFAULT '0000-00-00 00:00:00');
CREATE SEQUENCE tk_hour_detail_s START WITH 1000;

CREATE TABLE tk_hour_detail_t (TK_HOUR_DETAIL_ID NUMBER(38,0) NOT NULL, TK_TIME_BLOCK_ID NUMBER(38,0) NOT NULL, EARN_CODE VARCHAR2(3), HOURS DECIMAL(5,2), amount DECIMAL(6,2) DEFAULT 0, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, CONSTRAINT PK_TK_HOUR_DETAIL_T PRIMARY KEY (TK_HOUR_DETAIL_ID));
CREATE TABLE tk_missed_punch_doc_t (doc_hdr_id VARCHAR2(14) NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR DECIMAL(8,0) DEFAULT 1 NOT NULL, principal_id VARCHAR2(40) NOT NULL, clock_action VARCHAR2(20) NOT NULL, action_date TIMESTAMP DEFAULT to_date('0002-11-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL, action_time DATE DEFAULT to_date('00:00:00', 'HH24:MI:SS') NOT NULL, timesheet_doc_id VARCHAR2(14) NOT NULL, document_status VARCHAR2(1), tk_clock_log_id NUMBER(38,0), timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, assignment VARCHAR2(20) NOT NULL, CONSTRAINT PK_TK_MISSED_PUNCH_DOC_T PRIMARY KEY (doc_hdr_id));
CREATE SEQUENCE tk_missed_punch_s START WITH 1000;

CREATE TABLE tk_missed_punch_t (tk_missed_punch_id NUMBER(38,0) NOT NULL, principal_id VARCHAR2(40) NOT NULL, clock_action VARCHAR2(20) NOT NULL, action_date TIMESTAMP DEFAULT to_date('0002-11-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL, action_time DATE DEFAULT to_date('00:00:00', 'HH24:MI:SS') NOT NULL, timesheet_doc_id VARCHAR2(14) NOT NULL, document_id VARCHAR2(14), document_status VARCHAR2(1), tk_clock_log_id NUMBER(38,0), timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_TK_MISSED_PUNCH_T PRIMARY KEY (tk_missed_punch_id));
CREATE SEQUENCE tk_shift_differential_rl_s START WITH 1000;

CREATE TABLE tk_shift_differential_rl_t (TK_SHIFT_DIFF_RL_ID NUMBER(38,0) NOT NULL, LOCATION VARCHAR2(45), HR_SAL_GROUP VARCHAR2(10), pay_grade VARCHAR2(20), EFFDT DATE, EARN_CODE VARCHAR2(3), BEGIN_TS DATE, END_TS DATE, MIN_HRS DECIMAL(2,0), PY_CALENDAR_GROUP VARCHAR2(30) NOT NULL, MAX_GAP DECIMAL(5,2) DEFAULT 0, USER_PRINCIPAL_ID VARCHAR2(10), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, ACTIVE VARCHAR2(1) DEFAULT 'N', sun VARCHAR2(1) DEFAULT 'N' NOT NULL, mon VARCHAR2(1) DEFAULT 'N' NOT NULL, tue VARCHAR2(1) DEFAULT 'N' NOT NULL, wed VARCHAR2(1) DEFAULT 'N' NOT NULL, thu VARCHAR2(1) DEFAULT 'N' NOT NULL, fri VARCHAR2(1) DEFAULT 'N' NOT NULL, sat VARCHAR2(1) DEFAULT 'N' NOT NULL, from_earn_group VARCHAR2(10), CONSTRAINT PK_TK_SHIFT_DIFFERENTIAL_RL_T PRIMARY KEY (TK_SHIFT_DIFF_RL_ID));
CREATE SEQUENCE tk_system_lunch_rl_s START WITH 1000;

CREATE TABLE tk_system_lunch_rl_t (TK_SYSTEM_LUNCH_RL_ID NUMBER(38,0) NOT NULL, EFFDT DATE NOT NULL, TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, ACTIVE VARCHAR2(1), OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, USER_PRINCIPAL_ID VARCHAR2(10), SHOW_LUNCH_BUTTON VARCHAR2(1) DEFAULT '0', CONSTRAINT PK_TK_SYSTEM_LUNCH_RL_T PRIMARY KEY (TK_SYSTEM_LUNCH_RL_ID));
CREATE SEQUENCE tk_task_s START WITH 1000;

CREATE TABLE tk_task_t (tk_task_id NUMBER(38,0) NOT NULL, task NUMBER(38,0), work_area NUMBER(38,0), tk_work_area_id NUMBER(38,0) NOT NULL, descr VARCHAR2(45), admin_descr VARCHAR2(45), obj_id VARCHAR2(45), ver_nbr NUMBER(38,0) DEFAULT 1, USER_PRINCIPAL_ID VARCHAR2(40), effdt DATE NOT NULL, active VARCHAR2(1) DEFAULT 'Y' NOT NULL, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_TK_TASK_T PRIMARY KEY (tk_task_id));
CREATE SEQUENCE tk_time_block_hist_s START WITH 1000;

CREATE TABLE tk_time_block_hist_t (TK_TIME_BLOCK_HIST_ID NUMBER(38,0) NOT NULL, TK_TIME_BLOCK_ID NUMBER(38,0), DOCUMENT_ID VARCHAR2(14), principal_id VARCHAR2(40), JOB_NUMBER NUMBER(38,0), TASK NUMBER(38,0), WORK_AREA NUMBER(38,0), TK_WORK_AREA_ID NUMBER(38,0), TK_TASK_ID NUMBER(38,0), EARN_CODE VARCHAR2(3), BEGIN_TS TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL, BEGIN_TS_TZ VARCHAR2(50), END_TS TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL, END_TS_TZ VARCHAR2(50), CLOCK_LOG_CREATED VARCHAR2(1) DEFAULT 'Y', HOURS DECIMAL(5,2), USER_PRINCIPAL_ID VARCHAR2(40), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, ACTION_HISTORY VARCHAR2(15), MODIFIED_BY_PRINCIPAL_ID VARCHAR2(40), TIMESTAMP_MODIFIED TIMESTAMP DEFAULT '0000-00-00 00:00:00', OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, amount DECIMAL(6,2) DEFAULT 0, HR_JOB_ID NUMBER(38,0), CONSTRAINT PK_TK_TIME_BLOCK_HIST_T PRIMARY KEY (TK_TIME_BLOCK_HIST_ID));
CREATE SEQUENCE tk_time_block_s START WITH 1000;

CREATE TABLE tk_time_block_t (TK_TIME_BLOCK_ID NUMBER(38,0) NOT NULL, DOCUMENT_ID VARCHAR2(14), principal_id VARCHAR2(40), JOB_NUMBER NUMBER(38,0), WORK_AREA NUMBER(38,0), TASK NUMBER(38,0), TK_WORK_AREA_ID NUMBER(38,0), HR_JOB_ID NUMBER(38,0), TK_TASK_ID NUMBER(38,0), EARN_CODE VARCHAR2(3), BEGIN_TS TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL, BEGIN_TS_TZ VARCHAR2(50), clock_log_begin_id NUMBER(38,0), END_TS TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL, END_TS_TZ VARCHAR2(50), clock_log_end_id NUMBER(38,0), CLOCK_LOG_CREATED VARCHAR2(1) DEFAULT 'Y', HOURS DECIMAL(5,2), amount DECIMAL(6,2) DEFAULT 0, USER_PRINCIPAL_ID VARCHAR2(40), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36) NOT NULL, VER_NBR NUMBER(38,0) DEFAULT 1 NOT NULL, ovt_pref VARCHAR2(5), CONSTRAINT PK_TK_TIME_BLOCK_T PRIMARY KEY (TK_TIME_BLOCK_ID));
CREATE SEQUENCE tk_time_collection_rl_s START WITH 1000;

CREATE TABLE tk_time_collection_rl_t (TK_TIME_COLL_RULE_ID NUMBER(38,0) NOT NULL, DEPT VARCHAR2(21), WORK_AREA NUMBER(38,0), EFFDT DATE, CLOCK_USERS_FL VARCHAR2(1), HRS_DISTRIBUTION_FL VARCHAR2(1), USER_PRINCIPAL_ID VARCHAR2(10), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1, ACTIVE VARCHAR2(1) DEFAULT 'N', CONSTRAINT PK_TK_TIME_COLLECTION_RL_T PRIMARY KEY (TK_TIME_COLL_RULE_ID));
CREATE SEQUENCE tk_time_sheet_init_s START WITH 1000;

CREATE TABLE tk_time_sheet_init_t (tk_time_sheet_init_id NUMBER(38,0) NOT NULL, calendar_group VARCHAR2(30) NOT NULL, document_id NUMBER(38,0) NOT NULL, principal_id VARCHAR2(40) NOT NULL, py_calendar_entries_id NUMBER(38,0) NOT NULL, CONSTRAINT PK_TK_TIME_SHEET_INIT_T PRIMARY KEY (tk_time_sheet_init_id));
CREATE TABLE tk_user_pref_t (PRINCIPAL_ID VARCHAR2(40) NOT NULL, TIME_ZONE VARCHAR2(30), CONSTRAINT PK_TK_USER_PREF_T PRIMARY KEY (PRINCIPAL_ID));
CREATE TABLE tk_wa_maint_doc_t (doc_hdr_id VARCHAR2(50) NOT NULL, ver_nbr NUMBER(38,0), obj_id VARCHAR2(50), doc_cntnt CLOB, CONSTRAINT PK_TK_WA_MAINT_DOC_T PRIMARY KEY (doc_hdr_id));
CREATE SEQUENCE tk_weekly_overtime_rl_s START WITH 1000;

CREATE TABLE tk_weekly_overtime_rl_t (TK_WEEKLY_OVERTIME_RL_ID NUMBER(38,0) NOT NULL, max_hrs_ern_group VARCHAR2(10) NOT NULL, convert_from_ern_group VARCHAR2(10) NOT NULL, convert_to_erncd VARCHAR2(9) NOT NULL, EFFDT DATE, STEP DECIMAL(2,0), MAX_HRS DECIMAL(3,0), USER_PRINCIPAL_ID VARCHAR2(10), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1, ACTIVE VARCHAR2(1) DEFAULT 'N', TK_WEEKLY_OVT_GROUP_ID NUMBER(38,0) DEFAULT 1 NOT NULL, CONSTRAINT PK_TK_WEEKLY_OVERTIME_RL_T PRIMARY KEY (TK_WEEKLY_OVERTIME_RL_ID));
CREATE TABLE tk_weekly_ovt_group_t (TK_WEEKLY_OVERTIME_GROUP_ID NUMBER(38,0) NOT NULL, CONSTRAINT PK_TK_WEEKLY_OVT_GROUP_T PRIMARY KEY (TK_WEEKLY_OVERTIME_GROUP_ID));
CREATE TABLE tk_work_area_document_t (doc_hdr_id VARCHAR2(50) NOT NULL, ver_nbr NUMBER(38,0), obj_id VARCHAR2(50), CONSTRAINT PK_TK_WORK_AREA_DOCUMENT_T PRIMARY KEY (doc_hdr_id));
CREATE SEQUENCE tk_work_area_key_s START WITH 1000;

CREATE SEQUENCE tk_work_area_s START WITH 1000;

CREATE TABLE tk_work_area_t (TK_WORK_AREA_ID NUMBER(38,0) NOT NULL, work_area NUMBER(38,0) NOT NULL, DEPT VARCHAR2(21), EFFDT DATE NOT NULL, ACTIVE VARCHAR2(1), DESCR VARCHAR2(30), DEFAULT_OVERTIME_EARNCODE VARCHAR2(3), ADMIN_DESCR VARCHAR2(30), USER_PRINCIPAL_ID VARCHAR2(40), TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, OBJ_ID VARCHAR2(36), VER_NBR NUMBER(38,0) DEFAULT 1, OVERTIME_EDIT_ROLE VARCHAR2(20) NOT NULL, CONSTRAINT PK_TK_WORK_AREA_T PRIMARY KEY (TK_WORK_AREA_ID));
ALTER TABLE ca_account_t ADD PRIMARY KEY (FIN_COA_CD, ACCOUNT_NBR);
ALTER TABLE ca_object_code_t ADD PRIMARY KEY (UNIV_FISCAL_YR, FIN_COA_CD, FIN_OBJECT_CD);
ALTER TABLE ca_org_t ADD PRIMARY KEY (FIN_COA_CD, ORG_CD);
ALTER TABLE ca_sub_acct_t ADD PRIMARY KEY (FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR);
ALTER TABLE ca_sub_object_cd_t ADD PRIMARY KEY (UNIV_FISCAL_YR, FIN_COA_CD, ACCOUNT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD);
ALTER TABLE krns_adhoc_rte_actn_recip_t ADD PRIMARY KEY (RECIP_TYP_CD, ACTN_RQST_CD, ACTN_RQST_RECIP_ID, DOC_HDR_ID);
ALTER TABLE krns_sesn_doc_t ADD PRIMARY KEY (SESN_DOC_ID, DOC_HDR_ID, PRNCPL_ID, IP_ADDR);
ALTER TABLE qrtz_blob_triggers ADD PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE qrtz_cron_triggers ADD PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE qrtz_job_details ADD PRIMARY KEY (JOB_NAME, JOB_GROUP);
ALTER TABLE qrtz_job_listeners ADD PRIMARY KEY (JOB_NAME, JOB_GROUP, JOB_LISTENER);
ALTER TABLE qrtz_simple_triggers ADD PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE qrtz_trigger_listeners ADD PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_LISTENER);
ALTER TABLE qrtz_triggers ADD PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP);
CREATE UNIQUE INDEX CA_ACCOUNT_TC0 ON ca_account_t(OBJ_ID);
CREATE INDEX CA_ACCOUNT_TI2 ON ca_account_t(ACCOUNT_NBR, FIN_COA_CD);
CREATE UNIQUE INDEX CA_CHART_TC0 ON ca_chart_t(OBJ_ID);
CREATE UNIQUE INDEX CA_OBJECT_CODE_TC0 ON ca_object_code_t(OBJ_ID);
CREATE UNIQUE INDEX CA_ORG_TC0 ON ca_org_t(OBJ_ID);
CREATE UNIQUE INDEX CA_PROJECT_TC0 ON ca_project_t(OBJ_ID);
CREATE UNIQUE INDEX CA_SUB_ACCT_TC0 ON ca_sub_acct_t(OBJ_ID);
CREATE INDEX CA_SUB_ACCT_TI2 ON ca_sub_acct_t(FIN_COA_CD, ACCOUNT_NBR);
CREATE UNIQUE INDEX CA_SUB_OBJECT_CD_TC0 ON ca_sub_object_cd_t(OBJ_ID);
CREATE INDEX CA_SUB_OBJECT_CD_TI2 ON ca_sub_object_cd_t(UNIV_FISCAL_YR);
CREATE INDEX KRNS_ADHOC_RTE_ACTN_RECIP_T2 ON krns_adhoc_rte_actn_recip_t(DOC_HDR_ID);
CREATE UNIQUE INDEX KRNS_ADHOC_RTE_ACTN_RECIP_TC0 ON krns_adhoc_rte_actn_recip_t(OBJ_ID);
CREATE UNIQUE INDEX KRNS_ATT_TC0 ON krns_att_t(OBJ_ID);
CREATE UNIQUE INDEX KRNS_DOC_HDR_TC0 ON krns_doc_hdr_t(OBJ_ID);
CREATE INDEX KRNS_DOC_HDR_TI3 ON krns_doc_hdr_t(ORG_DOC_HDR_ID);
CREATE UNIQUE INDEX KRNS_LOOKUP_RSLT_TC0 ON krns_lookup_rslt_t(OBJ_ID);
CREATE UNIQUE INDEX KRNS_LOOKUP_SEL_TC0 ON krns_lookup_sel_t(OBJ_ID);
CREATE UNIQUE INDEX KRNS_MAINT_DOC_ATT_TC0 ON krns_maint_doc_att_t(OBJ_ID);
CREATE UNIQUE INDEX KRNS_MAINT_DOC_TC0 ON krns_maint_doc_t(OBJ_ID);
CREATE UNIQUE INDEX KRNS_MAINT_LOCK_TC0 ON krns_maint_lock_t(OBJ_ID);
CREATE INDEX KRNS_MAINT_LOCK_TI2 ON krns_maint_lock_t(DOC_HDR_ID);
CREATE UNIQUE INDEX KRNS_NTE_TC0 ON krns_nte_t(OBJ_ID);
CREATE UNIQUE INDEX KRNS_NTE_TYP_TC0 ON krns_nte_typ_t(OBJ_ID);
CREATE UNIQUE INDEX KRNS_PESSIMISTIC_LOCK_TC0 ON krns_pessimistic_lock_t(OBJ_ID);
CREATE INDEX KRNS_PESSIMISTIC_LOCK_TI1 ON krns_pessimistic_lock_t(DOC_HDR_ID);
CREATE INDEX KRNS_PESSIMISTIC_LOCK_TI2 ON krns_pessimistic_lock_t(PRNCPL_ID);
CREATE INDEX KRNS_SESN_DOC_TI1 ON krns_sesn_doc_t(LAST_UPDT_DT);
CREATE INDEX KREW_BAM_PARM_TI1 ON krsb_bam_parm_t(BAM_ID);
CREATE INDEX KRSB_BAM_TI1 ON krsb_bam_t(SVC_NM, MTHD_NM);
CREATE INDEX KRSB_BAM_TI2 ON krsb_bam_t(SVC_NM);
CREATE INDEX KRSB_MSG_QUE_TI1 ON krsb_msg_que_t(SVC_NM, SVC_MTHD_NM);
CREATE INDEX KRSB_MSG_QUE_TI2 ON krsb_msg_que_t(SVC_NMSPC, STAT_CD, IP_NBR, DT);
CREATE INDEX KRSB_SVC_DEF_TI1 ON krsb_svc_def_t(SRVR_IP, SVC_NMSPC);
CREATE UNIQUE INDEX KRSB_SVC_DEF_TI2 ON krsb_svc_def_t(FLT_SVC_DEF_ID);
CREATE INDEX qrtz_FIRED_TRIGGERS_TI1 ON qrtz_fired_triggers(JOB_GROUP);
CREATE INDEX qrtz_FIRED_TRIGGERS_TI2 ON qrtz_fired_triggers(JOB_NAME);
CREATE INDEX qrtz_FIRED_TRIGGERS_TI3 ON qrtz_fired_triggers(REQUESTS_RECOVERY);
CREATE INDEX qrtz_FIRED_TRIGGERS_TI4 ON qrtz_fired_triggers(IS_STATEFUL);
CREATE INDEX qrtz_FIRED_TRIGGERS_TI5 ON qrtz_fired_triggers(TRIGGER_GROUP);
CREATE INDEX qrtz_FIRED_TRIGGERS_TI6 ON qrtz_fired_triggers(INSTANCE_NAME);
CREATE INDEX qrtz_FIRED_TRIGGERS_TI7 ON qrtz_fired_triggers(TRIGGER_NAME);
CREATE INDEX qrtz_FIRED_TRIGGERS_TI8 ON qrtz_fired_triggers(TRIGGER_NAME, TRIGGER_GROUP);
CREATE INDEX qrtz_FIRED_TRIGGERS_TI9 ON qrtz_fired_triggers(IS_VOLATILE);
CREATE INDEX qrtz_JOB_DETAILS_TI1 ON qrtz_job_details(REQUESTS_RECOVERY);
CREATE INDEX qrtz_TRIGGERS_TI1 ON qrtz_triggers(NEXT_FIRE_TIME);
CREATE INDEX qrtz_TRIGGERS_TI2 ON qrtz_triggers(NEXT_FIRE_TIME, TRIGGER_STATE);
CREATE INDEX qrtz_TRIGGERS_TI3 ON qrtz_triggers(TRIGGER_STATE);
CREATE INDEX qrtz_TRIGGERS_TI4 ON qrtz_triggers(IS_VOLATILE);

ALTER TABLE krns_att_t ADD CONSTRAINT KRNS_ATT_TR1 FOREIGN KEY (NTE_ID) REFERENCES krns_nte_t (NTE_ID) ON UPDATE NO ACTION;
ALTER TABLE krns_maint_doc_t ADD CONSTRAINT KRNS_MAINT_DOC_TR1 FOREIGN KEY (DOC_HDR_ID) REFERENCES krns_doc_hdr_t (DOC_HDR_ID) ON UPDATE NO ACTION;
ALTER TABLE krns_nte_t ADD CONSTRAINT KRNS_NTE_TR1 FOREIGN KEY (NTE_TYP_CD) REFERENCES krns_nte_typ_t (NTE_TYP_CD) ON UPDATE NO ACTION;
ALTER TABLE qrtz_blob_triggers ADD CONSTRAINT qrtz_BLOB_TRIGGERS_TR1 FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (TRIGGER_NAME, TRIGGER_GROUP) ON UPDATE NO ACTION;
ALTER TABLE qrtz_cron_triggers ADD CONSTRAINT qrtz_CRON_TRIGGERS_TR1 FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (TRIGGER_NAME, TRIGGER_GROUP) ON UPDATE NO ACTION;
ALTER TABLE qrtz_job_listeners ADD CONSTRAINT KRSB_QUARTZ_JOB_LISTENERS_TR1 FOREIGN KEY (JOB_NAME, JOB_GROUP) REFERENCES qrtz_job_details (JOB_NAME, JOB_GROUP) ON UPDATE NO ACTION;
ALTER TABLE qrtz_simple_triggers ADD CONSTRAINT qrtz_SIMPLE_TRIGGERS_TR1 FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (TRIGGER_NAME, TRIGGER_GROUP) ON UPDATE NO ACTION;
ALTER TABLE qrtz_trigger_listeners ADD CONSTRAINT qrtz_TRIGGER_LISTENE_TR1 FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (TRIGGER_NAME, TRIGGER_GROUP) ON UPDATE NO ACTION;
