ALTER TABLE lm_leave_block_t CHANGE LEAVE_CODE EARN_CODE varchar(15) NOT NULL;
ALTER TABLE lm_leave_block_t CHANGE LM_LEAVE_CODE_ID HR_EARN_CODE_ID varchar(60) NOT NULL;
ALTER TABLE lm_leave_block_hist_t CHANGE LEAVE_CODE EARN_CODE varchar(15) NOT NULL;
ALTER TABLE lm_leave_block_hist_t CHANGE LM_LEAVE_CODE_ID HR_EARN_CODE_ID varchar(60) NOT NULL;