ALTER TABLE lm_sys_schd_timeoff_t CHANGE LEAVE_CODE EARN_CODE varchar(15) NOT NULL;
ALTER TABLE lm_sys_schd_timeoff_t CHANGE TRANSFER_TO_LEAVE_CODE TRANSFER_TO_EARN_CODE varchar(15) DEFAULT NULL;

