ALTER TABLE lm_leave_donation_t CHANGE DONATED_LV_CODE DONATED_ER_CODE varchar(15) DEFAULT NULL;
ALTER TABLE lm_leave_donation_t CHANGE RECIPIENTS_LV_CODE RECIPIENTS_ER_CODE varchar(15) DEFAULT NULL;

