ALTER TABLE `hr_job_t` CHANGE COLUMN `JOB_ID` `HR_JOB_ID` BIGINT(20) NOT NULL , DROP PRIMARY KEY , ADD PRIMARY KEY (`HR_JOB_ID`) ;
ALTER TABLE `hr_job_t` CHANGE COLUMN `TK_SAL_GROUP_ID` `TK_SAL_GROUP` VARCHAR(10) NULL DEFAULT NULL  ;
ALTER TABLE `hr_job_t` CHANGE COLUMN `dept_id` `dept` VARCHAR(21) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL  , CHANGE COLUMN `hr_paytype_id` `hr_paytype` VARCHAR(5) NULL DEFAULT NULL  ;

truncate table tk_dept_t;
ALTER TABLE `tk_dept_t` ADD COLUMN `dept` VARCHAR(21) NULL  AFTER `dept_id` , CHANGE COLUMN `dept_id` `dept_id` BIGINT(20) NOT NULL  ;
ALTER TABLE `tk_dept_t` ADD COLUMN `active` BIT(1) NULL  AFTER `CHART` , ADD COLUMN `effdt` DATE NULL  AFTER `CHART` , ADD COLUMN `timestamp` TIMESTAMP NULL  AFTER `effdt` ;
ALTER TABLE `tk_dept_t` CHANGE COLUMN `dept_id` `tk_dept_id` BIGINT(20) NOT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`tk_dept_id`) ;

CREATE TABLE `tk_dept_s` (
  `ID` bigint(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2090 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `tk_dept_earn_code_t` ADD COLUMN `active` BIT(1) NULL  AFTER `VER_NBR` , ADD COLUMN `effdt` DATE NULL  AFTER `active` , ADD COLUMN `timestamp` TIMESTAMP NULL  AFTER `effdt` , CHANGE COLUMN `dept_earn_code_id` `tk_dept_earn_code_id` BIGINT(20) NOT NULL  , CHANGE COLUMN `dept_id` `dept` VARCHAR(21) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL  , CHANGE COLUMN `tk_sal_group_id` `tk_sal_group` VARCHAR(10) NOT NULL  , CHANGE COLUMN `earn_code_id` `earn_code` VARCHAR(3) NOT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`tk_dept_earn_code_id`) ;


ALTER TABLE `tk_earn_code_t` ADD COLUMN `timestamp` TIMESTAMP NULL  AFTER `VER_NBR` ;

ALTER TABLE `tk_earn_group_t` ADD COLUMN `timestamp` TIMESTAMP NULL  AFTER `VER_NBR` , CHANGE COLUMN `earn_group_id` `tk_earn_group_id` BIGINT(20) NOT NULL  

, DROP PRIMARY KEY 

, ADD PRIMARY KEY (`tk_earn_group_id`) ;

ALTER TABLE `tk_earn_group_def_t` DROP COLUMN `effdt` , CHANGE COLUMN `earns_group` `tk_earn_group_id` BIGINT(20) NULL DEFAULT NULL  ;

ALTER TABLE `hr_paytype_t` ADD COLUMN `ACTIVE` BIT(1) NULL  AFTER `VER_NBR` , CHANGE COLUMN `PAYTYPE_ID` `HR_PAYTYPE_ID` BIGINT(20) NOT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`HR_PAYTYPE_ID`) ;

ALTER TABLE `tk_accruals_t` RENAME TO  `la_accruals_t` ;

ALTER TABLE `la_accruals_t` CHANGE COLUMN `TK_ACCRUALS_ID` `LA_ACCRUALS_ID` BIGINT(20) NOT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`LA_ACCRUALS_ID`) ;

ALTER TABLE `tk_accrual_categories_t` RENAME TO  `la_accrual_categories_t` ;

ALTER TABLE `la_accrual_categories_t` ADD COLUMN `TIMESTAMP` TIMESTAMP NULL  AFTER `ACTIVE` , CHANGE COLUMN `TK_ACCRUAL_CATEGORY_ID` `LA_ACCRUAL_CATEGORY_ID` BIGINT(20) NOT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`LA_ACCRUAL_CATEGORY_ID`) ;

ALTER TABLE `tk_assignment_t` ADD COLUMN `timestamp` TIMESTAMP NULL  AFTER `active` , CHANGE COLUMN `ASSIGNMENT_ID` `TK_ASSIGNMENT_ID` BIGINT(20) NOT NULL  , CHANGE COLUMN `EARN_CODE_ID` `EARN_CODE` VARCHAR(3) NULL DEFAULT NULL  , CHANGE COLUMN `WORK_AREA_ID` `WORK_AREA` BIGINT(10) NULL DEFAULT NULL  , CHANGE COLUMN `TASK_ID` `TASK` BIGINT(10) NULL DEFAULT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`TK_ASSIGNMENT_ID`) ;

ALTER TABLE `tk_assign_acct_t` CHANGE COLUMN `ASSIGN_ACCT_ID` `TK_ASSIGN_ACCT_ID` BIGINT(19) NOT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`TK_ASSIGN_ACCT_ID`) ;

ALTER TABLE `tk_assign_acct_t` DROP COLUMN `ACTIVE` , CHANGE COLUMN `ASSIGNMENT_ID` `TK_ASSIGNMENT_ID` BIGINT(19) NOT NULL  ;

ALTER TABLE `tk_clock_location_rl_t` CHANGE COLUMN `CLOCK_LOC_RULE_ID` `TK_CLOCK_LOC_RULE_ID` BIGINT(20) NOT NULL  , CHANGE COLUMN `WORK_AREA_ID` `WORK_AREA` BIGINT(10) NULL DEFAULT NULL  , CHANGE COLUMN `dept_id` `dept` VARCHAR(21) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  ;

ALTER TABLE `tk_daily_overtime_rl_t` CHANGE COLUMN `HR_PAYTYPE` `PAYTYPE` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  , CHANGE COLUMN `DEPTID` `DEPT` VARCHAR(21) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  , CHANGE COLUMN `WORK_AREA_ID` `WORK_AREA` BIGINT(10) NULL DEFAULT NULL  , CHANGE COLUMN `TASK_ID` `TASK` BIGINT(10) NULL DEFAULT NULL  ;

ALTER TABLE `tk_time_collection_rl_t` ADD COLUMN `ACTIVE` BIT(1) NULL  AFTER `VER_NBR` , CHANGE COLUMN `TIME_COLL_RULE_ID` `TK_TIME_COLL_RULE_ID` BIGINT(20) NOT NULL  , CHANGE COLUMN `DEPTID` `DEPT` VARCHAR(21) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  , CHANGE COLUMN `WORK_AREA_ID` `WORK_AREA` BIGINT(10) NULL DEFAULT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`TK_TIME_COLL_RULE_ID`) ;

ALTER TABLE `tk_grace_period_rl_t` CHANGE COLUMN `GRACE_PERIOD_RULE_ID` `TK_GRACE_PERIOD_RULE_ID` BIGINT(20) NULL DEFAULT NULL  ;

ALTER TABLE `tk_dept_lunch_rl_t` CHANGE COLUMN `DEPT_LUNCH_RULE_ID` `TK_DEPT_LUNCH_RL_ID` BIGINT(20) NOT NULL  , CHANGE COLUMN `DEPT_ID` `DEPT` VARCHAR(21) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  , CHANGE COLUMN `WORK_AREA_ID` `WORK_AREA` BIGINT(10) NULL DEFAULT NULL  , ADD PRIMARY KEY (`TK_DEPT_LUNCH_RL_ID`) ;

ALTER TABLE `tk_clock_log_t` ADD COLUMN `HR_JOB_ID` BIGINT(20) NULL  AFTER `IP_ADDRESS` , ADD COLUMN `TASK` BIGINT(10) NULL  AFTER `JOB_NUMBER` , ADD COLUMN `WORK_AREA` BIGINT(10) NULL  AFTER `JOB_NUMBER` , CHANGE COLUMN `CLOCK_LOG_ID` `TK_CLOCK_LOG_ID` BIGINT(20) NOT NULL  FIRST , CHANGE COLUMN `WORK_AREA_ID` `TK_WORK_AREA_ID` BIGINT(20) NULL DEFAULT NULL  , CHANGE COLUMN `TASK_ID` `TK_TASK_ID` BIGINT(20) NULL DEFAULT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`TK_CLOCK_LOG_ID`) ;

ALTER TABLE `tk_work_area_t` CHANGE COLUMN `WORK_AREA_ID` `TK_WORK_AREA_ID` BIGINT(20) NOT NULL  ;

ALTER TABLE `tk_work_area_t` ADD COLUMN `WORK_AREA` BIGINT(10) NOT NULL  AFTER `TK_WORK_AREA_ID` , CHANGE COLUMN `DEPT_ID` `DEPT` VARCHAR(21) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  AFTER `WORK_AREA` , CHANGE COLUMN `OVERTIME_PREFERENCE` `DEFAULT_OVERTIME_PREFERENCE` VARCHAR(3) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  ;

ALTER TABLE `tk_task_t` DROP COLUMN `active` , DROP COLUMN `effdt` , DROP COLUMN `timestamp` , ADD COLUMN `task` BIGINT(10) NULL  AFTER `tk_task_id` , ADD COLUMN `work_area` BIGINT(10) NULL  AFTER `task` , CHANGE COLUMN `task_id` `tk_task_id` BIGINT(20) NOT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`tk_task_id`) ;

ALTER TABLE `hr_work_schedule_t` CHANGE COLUMN `WORK_SCHEDULE_ID` `HR_WORK_SCHEDULE_ID` BIGINT(20) NOT NULL  , CHANGE COLUMN `DEPT_ID` `DEPT` VARCHAR(21) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  , CHANGE COLUMN `WORK_AREA_ID` `WORK_AREA` BIGINT(10) NULL DEFAULT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`HR_WORK_SCHEDULE_ID`) ;

ALTER TABLE `hr_work_schedule_entry_t` CHANGE COLUMN `WORK_SCHDULE_ENTRY_ID` `HR_WORK_SCHDULE_ENTRY_ID` BIGINT(20) NOT NULL  , CHANGE COLUMN `WORK_SCHEDULE_ID` `HR_WORK_SCHEDULE_ID` BIGINT(20) NOT NULL  , DROP PRIMARY KEY , ADD PRIMARY KEY (`HR_WORK_SCHDULE_ENTRY_ID`) ;

CREATE TABLE `tk_work_area_ovt_pref_t` (
  `tk_work_area_ovt_pref_id` bigint(20) NOT NULL,
  `tk_work_area_id` bigint(20) DEFAULT NULL,
  `paytype` varchar(5) COLLATE utf8_bin DEFAULT NULL,
  `overtime_preference` varchar(3) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`tk_work_area_ovt_pref_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `tk_work_area_ovt_pref_s` (
  `ID` bigint(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=1018 DEFAULT CHARSET=latin1;

ALTER TABLE `tk_time_block_t` CHANGE COLUMN `ERNCD` `EARN_CODE` VARCHAR(3) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  ;

ALTER TABLE `tk_time_block_t` ADD COLUMN `HR_JOB_ID` BIGINT(20) NULL  AFTER `TK_WORK_AREA_ID` , ADD COLUMN `TASK` BIGINT(20) NULL  AFTER `JOB_NUMBER` , ADD COLUMN `WORK_AREA` BIGINT(10) NULL  AFTER `JOB_NUMBER` , CHANGE COLUMN `WORK_AREA_ID` `TK_WORK_AREA_ID` BIGINT(20) NULL DEFAULT NULL  , CHANGE COLUMN `TASK_ID` `TK_TASK_ID` BIGINT(20) NULL DEFAULT NULL  ;

ALTER TABLE `tk_hour_detail_t` ENGINE = InnoDB , ADD COLUMN `hr_job_id` BIGINT(20) NULL  AFTER `ver_nbr` , ADD COLUMN `task` BIGINT(10) NULL  AFTER `hr_job_id` , ADD COLUMN `work_area` BIGINT(10) NULL  AFTER `hr_job_id` , CHANGE COLUMN `work_area_id` `tk_work_area_id` BIGINT(20) NULL DEFAULT NULL  , CHANGE COLUMN `task_id` `tk_task_id` BIGINT(20) NULL DEFAULT NULL  , CHANGE COLUMN `erncd` `earn_code` VARCHAR(3) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  ;

ALTER TABLE `tk_time_block_hist_t` ADD COLUMN `HR_JOB_ID` BIGINT(20) NULL  AFTER `amount` , ADD COLUMN `TASK` BIGINT(10) NULL  AFTER `JOB_NUMBER` , ADD COLUMN `WORK_AREA` BIGINT(10) NULL  AFTER `TASK` , CHANGE COLUMN `WORK_AREA_ID` `TK_WORK_AREA_ID` BIGINT(20) NULL DEFAULT NULL  , CHANGE COLUMN `TASK_ID` `TK_TASK_ID` BIGINT(20) NULL DEFAULT NULL  , CHANGE COLUMN `ERNCD` `EARN_CODE` VARCHAR(3) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL  ;





