ALTER TABLE `tk_document_header_t` ADD COLUMN `PAY_BEGIN_DT` DATE NULL  AFTER `DOCUMENT_STATUS` ;
ALTER TABLE `tk`.`tk_earn_code_t` CHANGE COLUMN `earn_code_id` `tk_earn_code_id` INT(11) NOT NULL, DROP PRIMARY KEY , ADD PRIMARY KEY (`tk_earn_code_id`) ;
ALTER TABLE `tk`.`tk_assignment_t` DROP COLUMN `EARN_CODE` ;
ALTER TABLE `tk`.`tk_assign_acct_t` ADD COLUMN `EARN_CODE` VARCHAR(3) NULL  AFTER `VER_NBR` ;

ALTER TABLE `tk`.`tk_sal_group_t` CHANGE COLUMN `SAL_GROUP_ID` `TK_SAL_GROUP_ID` BIGINT(20) NOT NULL  , DROP PRIMARY KEY, ADD PRIMARY KEY (`TK_SAL_GROUP_ID`) ;

ALTER TABLE `tk`.`tk_sal_group_t` CHANGE COLUMN `SAL_GROUP` `TK_SAL_GROUP` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL  ;
ALTER TABLE `tk`.`tk_task_t` CHANGE COLUMN `work_area_id` `tk_work_area_id` BIGINT(20) NOT NULL  ;

CREATE TABLE `tk_time_hour_detail_s` (
  `ID` bigint(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=1101 DEFAULT CHARSET=latin1;

CREATE TABLE `tk_time_hour_detail_t` (
  `TK_TIME_HOUR_DETAIL_ID` bigint(20) NOT NULL,
  `TK_TIME_BLOCK_ID` bigint(20) NOT NULL,
  `DOCUMENT_ID` varchar(14) COLLATE utf8_bin DEFAULT NULL,
  `JOB_NUMBER` bigint(20) DEFAULT NULL,
  `WORK_AREA` bigint(10) DEFAULT NULL,
  `TASK` bigint(20) DEFAULT NULL,
  `TK_WORK_AREA_ID` bigint(20) DEFAULT NULL,
  `HR_JOB_ID` bigint(20) DEFAULT NULL,
  `TK_TASK_ID` bigint(20) DEFAULT NULL,
  `EARN_CODE` varchar(3) COLLATE utf8_bin DEFAULT NULL,
  `BEGIN_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `BEGIN_TS_TZ` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `END_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `END_TS_TZ` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `CLOCK_LOG_CREATED` bit(1) DEFAULT b'0',
  `HOURS` decimal(5,2) DEFAULT NULL,
  `amount` decimal(6,2) DEFAULT '0.00',
  `USER_PRINCIPAL_ID` varchar(40) COLLATE utf8_bin DEFAULT NULL,
  `TIMESTAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `OBJ_ID` varchar(36) COLLATE utf8_bin NOT NULL,
  `VER_NBR` bigint(20) NOT NULL DEFAULT '1',
  PRIMARY KEY (`TK_TIME_HOUR_DETAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;





