ALTER TABLE `tk_document_header_t` ADD COLUMN `PAY_BEGIN_DT` DATE NULL  AFTER `DOCUMENT_STATUS` ;
ALTER TABLE `tk`.`tk_earn_code_t` CHANGE COLUMN `earn_code_id` `tk_earn_code_id` INT(11) NOT NULL, DROP PRIMARY KEY , ADD PRIMARY KEY (`tk_earn_code_id`) ;
ALTER TABLE `tk`.`tk_assignment_t` DROP COLUMN `EARN_CODE` ;
ALTER TABLE `tk`.`tk_assign_acct_t` ADD COLUMN `EARN_CODE` VARCHAR(3) NULL  AFTER `VER_NBR` ;

ALTER TABLE `tk`.`tk_sal_group_t` CHANGE COLUMN `SAL_GROUP_ID` `TK_SAL_GROUP_ID` BIGINT(20) NOT NULL  , DROP PRIMARY KEY, ADD PRIMARY KEY (`TK_SAL_GROUP_ID`) ;

ALTER TABLE `tk`.`tk_sal_group_t` CHANGE COLUMN `SAL_GROUP` `TK_SAL_GROUP` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL  ;
ALTER TABLE `tk`.`tk_task_t` CHANGE COLUMN `work_area_id` `tk_work_area_id` BIGINT(20) NOT NULL  ;