ALTER TABLE hr_job_t ADD COLUMN `comp_rate` DECIMAL(5,2) NULL DEFAULT 0.00  AFTER `VER_NBR` ;
ALTER TABLE `tk_daily_overtime_rl_t` CHANGE COLUMN `MAX_GAP` `MAX_GAP` DECIMAL(2,2) NULL DEFAULT NULL  ;
ALTER TABLE `tk_shift_differential_rl_t` CHANGE COLUMN `MAX_GAP` `MAX_GAP` DECIMAL(2,2) NULL DEFAULT NULL  ;



