ALTER TABLE tk_py_calendar_t ADD COLUMN `FLSA_BEGIN_DAY` VARCHAR(9) NOT NULL DEFAULT 'SUN';
ALTER TABLE tk_py_calendar_t ADD COLUMN `FLSA_BEGIN_TIME` TIME NOT NULL DEFAULT '0:00:00';

ALTER TABLE tk_system_lunch_rl_t CHANGE COLUMN `ACTIVE` `ACTIVE` VARCHAR(1) NULL DEFAULT NULL  ;
ALTER TABLE tk_shift_differential_rl_t DROP COLUMN `day0`,DROP COLUMN `day1`,DROP COLUMN `day2`,DROP COLUMN `day3`,
										DROP COLUMN `day4`,DROP COLUMN `day5`,DROP COLUMN `day6`,ADD COLUMN `sun` BIT(1) NOT NULL DEFAULT 0,
										ADD COLUMN `mon` BIT(1) NOT NULL DEFAULT 0,ADD COLUMN `tue` BIT(1) NOT NULL DEFAULT 0,ADD COLUMN `wed` BIT(1) NOT NULL DEFAULT 0,
										ADD COLUMN `thu` BIT(1) NOT NULL DEFAULT 0,ADD COLUMN `fri` BIT(1) NOT NULL DEFAULT 0,ADD COLUMN `sat` BIT(1) NOT NULL DEFAULT 0;
	
ALTER TABLE hr_paytype_t DROP COLUMN `CALENDAR_GROUP`, DROP COLUMN `HOLIDAY_CALENDAR_GROUP`;

ALTER TABLE tk_daily_overtime_rl_t CHANGE COLUMN `active` `active` VARCHAR(1) NULL DEFAULT 'N'  ;

ALTER TABLE hr_paytype_t CHANGE COLUMN `ACTIVE` `ACTIVE` VARCHAR(1) NULL DEFAULT 'N'  ;

ALTER TABLE hr_work_schedule_t CHANGE COLUMN `ACTIVE` `ACTIVE` VARCHAR(1) NULL DEFAULT 'N'  ;
ALTER TABLE tk_assignment_t CHANGE COLUMN `active` `active` VARCHAR(1) NULL DEFAULT 'N'  ;
ALTER TABLE tk_dept_t CHANGE COLUMN `active` `active` VARCHAR(1) NULL DEFAULT 'N'  ;
ALTER TABLE tk_roles_t CHANGE COLUMN `active` `active` VARCHAR(1) NULL DEFAULT 'N'  ;
ALTER TABLE tk_shift_differential_rl_t CHANGE COLUMN `ACTIVE` `ACTIVE` VARCHAR(1) NULL DEFAULT 'N'  ;
ALTER TABLE tk_time_collection_rl_t CHANGE COLUMN `ACTIVE` `ACTIVE` VARCHAR(1) NULL DEFAULT 'N'  ;
ALTER TABLE tk_weekly_overtime_rl_t CHANGE COLUMN `ACTIVE` `ACTIVE` VARCHAR(1) NULL DEFAULT 'N'  ;

