--RICE Client Upgrade--
ALTER TABLE "EDO"."KRNS_PESSIMISTIC_LOCK_T" ADD "SESN_ID" VARCHAR2(40) DEFAULT '' NOT NULL;

--Addition of EDO_REVIEW_LAYER_DEF_T--
CREATE SEQUENCE  "EDO"."EDO_REVIEW_LAYER_DEF_ID_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  ORDER  NOCYCLE ;

CREATE TABLE "EDO"."EDO_REVIEW_LAYER_DEF_T"
   (	"REVIEW_LAYER_DEF_ID" NUMBER(8,0) NOT NULL,
	"NODE_NAME" VARCHAR2(30 BYTE) NOT NULL,
	"VOTE_TYPE" VARCHAR2(16 BYTE) NOT NULL,
	"DESCRIPTION" CLOB,
	"REVIEW_LETTER" CHAR(1 BYTE) NOT NULL,
	"CREATE_DATE" DATE NOT NULL,
	"CREATED_BY" VARCHAR2(16 BYTE) NOT NULL,
	"LAST_UPDATED_DATE" DATE,
	"UPDATED_BY" VARCHAR2(16 BYTE),
	"OBJ_ID" VARCHAR2(36 BYTE),
	"VER_NBR" NUMBER(38,0),
	CONSTRAINT "EDO_REVIEW_LAYER_DEF_T_PK" PRIMARY KEY ("REVIEW_LAYER_DEF_ID"));

CREATE OR REPLACE TRIGGER "EDO"."EDO_REVIEW_LAYER_DEF_TR"
   before insert on "EDO_REVIEW_LAYER_DEF_T"
   for each row
begin
   if inserting then
      if :NEW."REVIEW_LAYER_DEF_ID" is null then
         select EDO_REVIEW_LAYER_DEF_ID_S.nextval into :NEW."REVIEW_LAYER_DEF_ID" from dual;
      end if;
   end if;
end;

--Addition of EDO_DOSSIER_DOCUMENT_T--
CREATE TABLE "EDO"."EDO_DOSSIER_DOCUMENT_T"
   (	"DOCUMENT_ID" VARCHAR(14 BYTE) NOT NULL,
    "DOSSIER_ID" NUMBER(8, 0),
	"PRINCIPAL_ID" VARCHAR2(40 BYTE),
	"DOCUMENT_STATUS" VARCHAR2(1 BYTE),
	"OBJ_ID" VARCHAR2(36 BYTE),
	"VER_NBR" NUMBER(38,0),
	CONSTRAINT "EDO_DOSSIER_DOCUMENT_PK" PRIMARY KEY ("DOCUMENT_ID"));

--Adding column to EDO_DOSSIER_TYPE_T--
ALTER TABLE EDO_DOSSIER_TYPE_T ADD DOC_TYPE_NAME VARCHAR2(64);

--Adding column to EDO_REVIEW_LAYER_DEF_T--
ALTER TABLE EDO_REVIEW_LAYER_DEF_T ADD ROUTE_LEVEL NUMBER(3,0);

--Adding column to EDO_REVIEW_LAYER_DEF_T--
ALTER TABLE EDO_REVIEW_LAYER_DEF_T ADD REVIEW_LEVEL NUMBER(3,0);

--Drop column from EDO_VOTE_RECORD_T--
ALTER TABLE EDO_VOTE_RECORD_T DROP COLUMN AOE_CODE;

--Adding column to EDO_DOSSIER_DOCUMENT_T--
ALTER TABLE EDO_DOSSIER_DOCUMENT_T ADD DOC_TYPE_NAME VARCHAR(64);

--Adding column to EDO_VOTE_RECORD_T--
ALTER TABLE EDO_VOTE_RECORD_T ADD AOE_CODE VARCHAR(1);

--Data Updates--
UPDATE EDO_DOSSIER_TYPE_T SET DOC_TYPE_NAME = 'TenureProcessDocument' WHERE DOSSIER_TYPE_NAME = 'Tenure';
UPDATE EDO_DOSSIER_TYPE_T SET DOC_TYPE_NAME = 'PromotionProcessDocument' WHERE DOSSIER_TYPE_NAME = 'Promotion';

--Drop old document table--
DROP TABLE EDO_DOCUMENT_T;

--Drop column from EDO_DOSSIER_T--
ALTER TABLE EDO_DOSSIER_T DROP COLUMN ROUTING_ID;

--Drop column from view--
CREATE OR REPLACE VIEW "EDO_CANDIDATEDOSSIER_V" AS select c.first_name, c.last_name, c.username, c.candidacy_campus, c.candidacy_school,
       c.candidacy_year, c.candidate_id, c.current_rank, c.primary_department_id,
       d.dossier_id, d.dossier_status, d.rank_sought, d.due_date, d.document_id
  from edo_candidate_t c inner join edo_dossier_t d on c.username = d.candidate_username;