Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Ricketts','Rowland','Assistant Professor','BL-FINS','BL-FINS',2013,'BL-ARSC','BL','rickettr');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Nakagawa','James','Assistant Professor','BL-FINS','BL-FINS',2013,'BL-ARSC','BL','onakagaw');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Brunner','Paul','Associate Professor','BL-THTR','BL-THTR',2013,'BL-ARSC','BL','pbrunner');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'LaBolt','Terry','Assistant Professor','BL-THTR','BL-THTR',2013,'BL-ARSC','BL','tlabolt');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Pisano','Linda','Assistant Professor','BL-THTR','BL-THTR',2013,'BL-ARSC','BL','lpisano');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Hackenberg','Amy','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','ahackenb');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Maltese','Adam','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','amaltese');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Schertz','Hannah','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','hschertz');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'McCormick','Alexander','Associate Professor','BL-ELPS','BL-ELPS',2013,'BL-EDUC','BL','amcc');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Cho','Yonjoo','Associate Professor','BL-ISTE','BL-ISTE',2013,'BL-EDUC','BL','choyonj');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Haynes','Ray','Associate Professor','BL-ISTE','BL-ISTE',2013,'BL-EDUC','BL','rkhaynes');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Adomat','Donna','Associate Professor','BL-LGED','BL-LGED',2013,'BL-EDUC','BL','dadomat');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Samuelson','Beth','Associate Professor','BL-LGED','BL-LGED',2013,'BL-EDUC','BL','blsamuel');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Buck','Gayle','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','gabuck');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Galindo','Enrique','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','egalindo');
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Butera','Gretchen','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','gbutera');
                                
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Malae','Naga','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','nrmalae');
                                
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Shah','Akash','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','aknshah');
                                
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Pirkola','Derek','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','dpirkola');

Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Whitakar','Maria','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','mcwhitak');
                                
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Susan','McCammon','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','smccammo');
                                
Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Bradley','Tribble','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','bradleyt');

Insert into EDO.EDO_CANDIDATE_T (CANDIDATE_ID,LAST_NAME,FIRST_NAME,CURRENT_RANK,PRIMARY_DEPARTMENT_ID,TNP_DEPARTMENT_ID,CANDIDACY_YEAR,CANDIDACY_SCHOOL,CANDIDACY_CAMPUS,USERNAME) values 
                                (CANDIDATE_ID_S.nextval,'Lee','Kenneth','Associate Professor','BL-CRIN','BL-CRIN',2013,'BL-EDUC','BL','lee55');
commit;