--Creation SQL
SET DEFINE OFF;
INSERT INTO krcr_nmspc_t (nmspc_cd, obj_id, ver_nbr, nm, actv_ind, appl_id) VALUES ('EDO', sys_guid(), '1', 'eDossier', 'Y', 'EDO');
INSERT INTO krim_typ_t (kim_typ_id, obj_id, ver_nbr, nm, srvc_nm, actv_ind, nmspc_cd) VALUES (krim_typ_id_s.nextval, sys_guid(), '1', 'Reviewer Role', '{EDO}edoReviewerRoleTypeService', 'Y', 'EDO');
INSERT INTO krim_typ_t (kim_typ_id, obj_id, ver_nbr, nm, srvc_nm, actv_ind, nmspc_cd) VALUES (krim_typ_id_s.nextval, sys_guid(), '1', 'Candidate Role', '{EDO}edoCandidateRoleTypeService', 'Y', 'EDO');
INSERT INTO krim_typ_t (kim_typ_id, obj_id, ver_nbr, nm, srvc_nm, actv_ind, nmspc_cd) VALUES (krim_typ_id_s.nextval, sys_guid(), '1', 'Guest Role', '{EDO}edoGuestRoleTypeService', 'Y', 'EDO');
INSERT INTO krim_typ_t (kim_typ_id, obj_id, ver_nbr, nm, srvc_nm, actv_ind, nmspc_cd) VALUES (krim_typ_id_s.nextval, sys_guid(), '1', 'Candidate Delegate Role', '{EDO}edoCandidateDelegateRoleTypeService', 'Y', 'EDO');
INSERT INTO krim_typ_t (kim_typ_id, obj_id, ver_nbr, nm, srvc_nm, actv_ind, nmspc_cd) VALUES (krim_typ_id_s.nextval, sys_guid(), '1', 'Committee Chair Delegate Role', '{EDO}edoCommitteeChairDelegateRoleTypeService', 'Y', 'EDO');
INSERT INTO krim_typ_t (kim_typ_id, obj_id, ver_nbr, nm, srvc_nm, actv_ind, nmspc_cd) VALUES (krim_typ_id_s.nextval, sys_guid(), '1', 'Review Committee Chair Role', '{EDO}edoReviewCommitteeChairRoleTypeService', 'Y', 'EDO');
INSERT INTO krim_typ_t (kim_typ_id, obj_id, ver_nbr, nm, srvc_nm, actv_ind, nmspc_cd) VALUES (krim_typ_id_s.nextval, sys_guid(), '1', 'SuperUser Role', '{EDO}edoSuperUserRoleTypeService', 'Y', 'EDO');
INSERT INTO krim_typ_t (kim_typ_id, obj_id, ver_nbr, nm, srvc_nm, actv_ind, nmspc_cd) VALUES (krim_typ_id_s.nextval, sys_guid(), '1', 'Administrator', '{EDO}edoAdministratorRoleTypeService', 'Y', 'EDO');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleReviewerDeptId', 'EDO Role Reviewer Department ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleReviewerSchoolId', 'EDO Role Reviewer School ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleReviewerCampusId', 'EDO Role Reviewer Campus ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleGuestDossierId', 'EDO Role Guest Dossier ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleChairDeptId', 'EDO Role Chair Department ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleChairSchoolId', 'EDO Role Chair School ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleChairCampusId', 'EDO Role Chair Campus ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleAdministratorDeptId', 'EDO Role Administrator Department ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleAdministratorSchoolId', 'EDO Role Administrator School ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleAdministratorCampusId', 'EDO Role Administrator Campus ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleCandidateDelegateDossierId', 'EDO Role Candidate Delegate Dossier ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleChairDelegateDeptId', 'EDO Role Chair Delegate Department ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleChairDelegateSchoolId', 'EDO Role Chair Delegate School ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleChairDelegateCampusId', 'EDO Role Chair Delegater Campus ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleChairDelegateUniversityId', 'EDO Role Chair Delegater University ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_attr_defn_t (kim_attr_defn_id, obj_id, ver_nbr, nm, lbl, actv_ind, nmspc_cd, cmpnt_nm) VALUES (krim_attr_defn_id_s.nextval, sys_guid(), '1', 'edoRoleChairUniversityId', 'EDO Role Chair University ID', 'Y', 'EDO', 'org.kuali.kpme.edo.kim.EDOKimAttributes');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'a', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Reviewer Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleReviewerDeptId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'b', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Reviewer Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleReviewerSchoolId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'c', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Reviewer Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleReviewerCampusId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'a', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Guest Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleGuestDossierId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'a', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Candidate Delegate Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleCandidateDelegateDossierId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'a', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Committee Chair Delegate Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairDelegateDeptId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'b', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Committee Chair Delegate Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairDelegateSchoolId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'c', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Committee Chair Delegate Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairDelegateCampusId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'd', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Committee Chair Delegate Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairDelegateUniversityId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'a', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairDeptId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'b', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairSchoolId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'c', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairCampusId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'd', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairUniversityId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'a', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Administrator'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleAdministratorDeptId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'b', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Administrator'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleAdministratorSchoolId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'c', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Administrator'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleAdministratorCampusId'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_CANDIDATE', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Candidate Role'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_REVIEWER', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Reviewer Role'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_GUEST', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Guest Role'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_CANDIDATE_DELEGATE', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Candidate Delegate Role'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_ADMINISTRATOR', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Administrator'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_COMMITTEE_CHAIR', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_SUPERUSER', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'SuperUser Role'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_CHAIR_DELEGATE', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Committee Chair Delegate Role'), 'Y');
INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SUPERUSER'), ('ADS:BL-UITS-HRMS-JAVA-TEAM'), 'G', NULL, NULL, SYSDATE);
INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SUPERUSER'), ('ADS:BL-UITS-HRMS-PS-TECH-TEAM'), 'G', NULL, NULL, SYSDATE);
INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SUPERUSER'), (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'aknshah'), 'P', NULL, NULL, SYSDATE);
INSERT INTO krim_perm_t (perm_id, obj_id, ver_nbr, perm_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_perm_id_s.nextval, sys_guid(), '1', (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-IDM' AND nm = 'Assign Role'), 'EDO', 'Assign Role', '', 'Y');
INSERT INTO krim_perm_t (perm_id, obj_id, ver_nbr, perm_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_perm_id_s.nextval, sys_guid(), '1', (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-SYS' AND nm = 'Initiate Document'), 'EDO', 'Initiate Role Document', '', 'Y');
INSERT INTO krim_perm_t (perm_id, obj_id, ver_nbr, perm_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_perm_id_s.nextval, sys_guid(), '1', (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-IDM' AND nm = 'Grant Permission'), 'EDO', 'Grant Permission', '', 'Y');
INSERT INTO krim_perm_attr_data_t (attr_data_id, obj_id, ver_nbr, perm_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Assign Role' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-IDM' AND nm = 'Assign Role')), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-IDM' AND nm = 'Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-NS' AND nm = 'namespaceCode'), 'EDO');
INSERT INTO krim_perm_attr_data_t (attr_data_id, obj_id, ver_nbr, perm_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Initiate Role Document' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-SYS' AND nm = 'Initiate Document')), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-SYS' AND nm = 'Document Type (Permission)'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'documentTypeName'), 'IdentityManagementDocument');
INSERT INTO krim_perm_attr_data_t (attr_data_id, obj_id, ver_nbr, perm_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Grant Permission' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-IDM' AND nm = 'Grant Permission')), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-IDM' AND nm = 'Permission'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-NS' AND nm = 'namespaceCode'), 'EDO');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SUPERUSER'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Assign Role' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-IDM' AND nm = 'Assign Role')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SUPERUSER'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Initiate Role Document' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-SYS' AND nm = 'Initiate Document')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SUPERUSER'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Grant Permission' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-IDM' AND nm = 'Grant Permission')), 'Y');
INSERT INTO krim_rsp_tmpl_t (rsp_tmpl_id, obj_id, ver_nbr, nmspc_cd, nm, kim_typ_id, desc_txt, actv_ind) VALUES (krim_rsp_tmpl_id_s.nextval, sys_guid(), '1', 'EDO', 'edoSubmitDossier', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Candidate Role'), 'Submit Dossier', 'Y');
INSERT INTO krim_rsp_tmpl_t (rsp_tmpl_id, obj_id, ver_nbr, nmspc_cd, nm, kim_typ_id, desc_txt, actv_ind) VALUES (krim_rsp_tmpl_id_s.nextval, sys_guid(), '1', 'EDO', 'edoDeptApprove', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), 'Dept Approve', 'Y');
INSERT INTO krim_rsp_tmpl_t (rsp_tmpl_id, obj_id, ver_nbr, nmspc_cd, nm, kim_typ_id, desc_txt, actv_ind) VALUES (krim_rsp_tmpl_id_s.nextval, sys_guid(), '1', 'EDO', 'edoSchoolApprove', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), 'School Approve', 'Y');
INSERT INTO krim_rsp_tmpl_t (rsp_tmpl_id, obj_id, ver_nbr, nmspc_cd, nm, kim_typ_id, desc_txt, actv_ind) VALUES (krim_rsp_tmpl_id_s.nextval, sys_guid(), '1', 'EDO', 'edoCampusApprove', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), 'Campus Approve', 'Y');
INSERT INTO krim_rsp_tmpl_t (rsp_tmpl_id, obj_id, ver_nbr, nmspc_cd, nm, kim_typ_id, desc_txt, actv_ind) VALUES (krim_rsp_tmpl_id_s.nextval, sys_guid(), '1', 'EDO', 'edoCloseDossier', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), 'Close Dossier', 'Y');
INSERT INTO krim_rsp_t (rsp_id, obj_id, ver_nbr, rsp_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_rsp_id_s.nextval, sys_guid(), '1', (SELECT rsp_tmpl_id FROM krim_rsp_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'edoSubmitDossier' AND kim_typ_id = (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Candidate Role')), 'EDO', 'SubmitDossier', '', 'Y');
INSERT INTO krim_rsp_t (rsp_id, obj_id, ver_nbr, rsp_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_rsp_id_s.nextval, sys_guid(), '1', (SELECT rsp_tmpl_id FROM krim_rsp_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'edoDeptApprove' AND kim_typ_id = (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role')), 'EDO', 'DeptApprove', '', 'Y');
INSERT INTO krim_rsp_t (rsp_id, obj_id, ver_nbr, rsp_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_rsp_id_s.nextval, sys_guid(), '1', (SELECT rsp_tmpl_id FROM krim_rsp_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'edoSchoolApprove' AND kim_typ_id = (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role')), 'EDO', 'SchoolApprove', '', 'Y');
INSERT INTO krim_rsp_t (rsp_id, obj_id, ver_nbr, rsp_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_rsp_id_s.nextval, sys_guid(), '1', (SELECT rsp_tmpl_id FROM krim_rsp_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'edoCampusApprove' AND kim_typ_id = (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role')), 'EDO', 'CampusApprove', '', 'Y');
INSERT INTO krim_rsp_t (rsp_id, obj_id, ver_nbr, rsp_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_rsp_id_s.nextval, sys_guid(), '1', (SELECT rsp_tmpl_id FROM krim_rsp_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'edoCloseDossier' AND kim_typ_id = (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role')), 'EDO', 'CloseDossier', '', 'Y');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'DeptApprove'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairDeptId'), '');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'SchoolApprove'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairSchoolId'), '');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'CampusApprove'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairCampusId'), '');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'CloseDossier'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Review Committee Chair Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoRoleChairUniversityId'), '');


INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'rickettr'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'onakagaw'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'pbrunner'), 'P', NULL, NULL, SYSDATE);


INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'tlabolt'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'lpisano'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'ahackenb'), 'P', NULL, NULL, SYSDATE);


INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'amaltese'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'hschertz'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'amcc'), 'P', NULL, NULL, SYSDATE);


INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'choyonj'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'rkhaynes'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'dadomat'), 'P', NULL, NULL, SYSDATE);


INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'blsamuel'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'gabuck'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'egalindo'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'gbutera'), 'P', NULL, NULL, SYSDATE);

INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'nrmalae'), 'P', NULL, NULL, SYSDATE);
INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'bradleyt'), 'P', NULL, NULL, SYSDATE);
INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'lee55'), 'P', NULL, NULL, SYSDATE);
INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'aknshah'), 'P', NULL, NULL, SYSDATE);
INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'mcwhitak'), 'P', NULL, NULL, SYSDATE);
INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'dpirkola'), 'P', NULL, NULL, SYSDATE);
INSERT INTO krim_role_mbr_t (role_mbr_id, ver_nbr, obj_id, role_id, mbr_id, mbr_typ_cd, actv_frm_dt, actv_to_dt, last_updt_dt) VALUES (krim_role_mbr_id_s.nextval, '1', sys_guid(), (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CANDIDATE'), 
                                                                                                                                      (SELECT prncpl_id FROM krim_prncpl_t WHERE prncpl_nm = 'smccammo'), 'P', NULL, NULL, SYSDATE);


