INSERT INTO "EDO_CHECKLIST_SECTION_T"("CHECKLIST_SECTION_ID", "CHECKLIST_ID", "DESCRIPTION", "CREATE_DATE", "CREATED_BY", "LAST_UPDATE_DATE", "UPDATED_BY", "CHECKLIST_SECTION_NAME", "CHECKLIST_SECTION_ORDINAL")
  VALUES(21, 1, 'Reconsideration items', TO_DATE('2014-01-22 08:00:00','YYYY-MM-DD HH24:MI:SS'), 1, TO_DATE('2014-01-22 08:00:00','YYYY-MM-DD HH24:MI:SS'), 1, 'Reconsideration Items', 6)
GO
INSERT INTO "EDO_CHECKLIST_ITEM_T"("CHECKLIST_SECTION_ID", "DESCRIPTION", "REQUIRED", "CREATE_DATE", "CREATED_BY", "LAST_UPDATE_DATE", "UPDATED_BY", "CHECKLIST_ITEM_NAME", "CHECKLIST_ITEM_SECTION_ORDINAL")
  VALUES(21, 'Include any items in support of the reconsideration of the dossier', 0, TO_DATE('2014-01-22 00:00:00','YYYY-MM-DD HH24:MI:SS'), 1, TO_DATE('1014-01-22 00:00:00','YYYY-MM-DD HH24:MI:SS'), 1, 'Reconsideration Supporting Items', 1)
GO
