ALTER TABLE tk_clock_location_rl_t CHANGE COLUMN `active` `active` VARCHAR(1) NULL DEFAULT NULL  ;
ALTER TABLE tk_daily_overtime_rl_t CHANGE COLUMN `ACTIVE` `ACTIVE` VARCHAR(1) NULL DEFAULT NULL  ;

ALTER TABLE hr_earn_group_t ADD COLUMN `show_summary` VARCHAR(1) NULL DEFAULT 'N'  AFTER `descr` ;

ALTER TABLE tk_system_lunch_rl_t DROP COLUMN `BLOCK_HOURS` , DROP COLUMN `MIN_MINS` , ADD COLUMN `SHOW_LUNCH_BUTTON` VARCHAR(1) NULL DEFAULT '0'  AFTER `USER_PRINCIPAL_ID` ;
ALTER TABLE tk_dept_lunch_rl_t DROP COLUMN `REQUIRED_CLOCK_FL`;
ALTER TABLE tk_dept_lunch_rl_t ADD COLUMN `SHIFT_HOURS` DECIMAL(2,1) NULL DEFAULT NULL  ;
ALTER TABLE tk_dept_lunch_rl_t ADD COLUMN `DEDUCTION_MINS` DECIMAL(3,0) NULL DEFAULT NULL  ;
ALTER TABLE tk_dept_lunch_rl_t CHANGE COLUMN `active` `active` VARCHAR(1) NULL DEFAULT NULL  ;



