DROP TABLE IF EXISTS `tk_batch_job_entry_s`;
CREATE TABLE `tk_batch_job_entry_s` (
  `id` bigint(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2085 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `tk_batch_job_entry_t`;
CREATE TABLE `tk_batch_job_entry_t` (
  `TK_BATCH_JOB_ENTRY_ID` bigint(20) NOT NULL,
  `TK_BATCH_JOB_ID` bigint(20) NOT NULL,
  `DOCUMENT_ID` varchar(40) NOT NULL,
  `PRINCIPAL_ID` varchar(40) NOT NULL,
  `BATCH_JOB_ENTRY_STATUS` VARCHAR(1) NOT NULL,
  `TK_PY_CALENDAR_ENTRY_ID` BIGINT(20) NOT NULL,
  `BATCH_JOB_EXCEPTION` varchar(100) NOT NULL,
  `IP_ADDRESS` varchar(20) NOT NULL,
  `BATCH_JOB_NAME` varchar(40) NOT NULL,
  PRIMARY KEY (`TK_BATCH_JOB_ENTRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;