
ALTER TABLE `lm_leave_plan_t` MODIFY COLUMN `DESCR` VARCHAR(30)  CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
 MODIFY COLUMN `CAL_YEAR_START` VARCHAR(5)  CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
