delete from lm_leave_plan_t where LM_LEAVE_PLAN_ID >= '8000';
delete from lm_accrual_category_t where lm_accrual_category_id >= '5000';
delete from lm_accrual_category_rules_t where lm_accrual_category_rules_id >= '5000';
delete from lm_leave_code_t where lm_leave_code_id >= '5000';
delete from hr_earn_code_t where hr_earn_code_id >= '5000';
delete from hr_principal_attributes_t where principal_id like('testUser%');
delete from hr_job_t where hr_job_id >= '5000';
delete from lm_leave_block_t where principal_id like('testUser%');
delete from lm_leave_block_hist_t where principal_id like('testUser%');
delete from lm_prin_accr_ran_t where principal_id = 'testUser';